//! Export wrappers and headers (T4-3, spec §14.2): the public C API of each
//! exported flow and function.

use std::fmt::Write as _;

use onsa_core::{FnId, Mode, Ty};

use crate::emit::{Cx, Export, R, f32_lit};
use crate::names::{ident, qualified};
use crate::{PanicMode, no_span, unsupported};

/// The public header `onsa_<flow>.h`.
pub(crate) fn header(cx: &mut Cx, e: &Export) -> R<String> {
    let meta = &cx.m.flows[e.meta_index];
    let fns = meta.fns.clone();
    let sym = e.symbol.clone();
    let up = e.upper.clone();
    let mut h = String::new();
    let _ = writeln!(h, "/* {sym}.h — generated by onsa build for the flow `{}`; do not edit. */", meta.name);
    let _ = writeln!(h, "#ifndef {up}_H");
    let _ = writeln!(h, "#define {up}_H");
    let _ = writeln!(h, "#ifndef {}\n#define {}\n#endif", cx.opts.panic.define(), cx.opts.panic.define());
    let _ = writeln!(h, "#include \"{}\"", crate::RUNTIME_HEADER_NAME);
    let _ = writeln!(h, "#ifdef __cplusplus\nextern \"C\" {{\n#endif\n");
    let _ = writeln!(h, "#define {up}_SIZE      {}   /* bytes of the fast region (spec §12.4) */", e.layout.size);
    let _ = writeln!(h, "#define {up}_BULK_SIZE {}   /* bytes of the bulk region */", e.layout.bulk_size);
    let _ = writeln!(h, "#define {up}_ALIGN     {}", e.layout.align);
    let _ = writeln!(h, "#define {up}_PARAM_COUNT {}\n", meta.params.len());
    let _ = writeln!(h, "typedef struct {sym} {sym};   /* the state (fast region); opaque */");
    // Params struct with the input names (spec §14.2).
    let pfields = cx.fields(fns.params).to_vec();
    let _ = write!(h, "typedef struct {sym}_params {{");
    if pfields.is_empty() {
        let _ = write!(h, " uint8_t onsa_empty;");
    }
    for (name, ty) in &pfields {
        let tn = scalar_c(cx, ty, &format!("the `Ctl` input `{name}`"))?;
        let _ = write!(h, " {tn} {};", ident(name));
    }
    let _ = writeln!(h, " }} {sym}_params;\n");
    let cfg = config_args(cx, fns.config)?;
    let _ = writeln!(
        h,
        "/* Memory is the caller's: `s` has {up}_SIZE bytes aligned to {up}_ALIGN, `bulk` has {up}_BULK_SIZE (NULL when 0). */"
    );
    let _ = writeln!(
        h,
        "/* 0: ok, 1: `init` panicked (panic = \"poison\" only): the state is left uninitialized — `process` returns 1\n * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */"
    );
    let _ = writeln!(h, "int  {sym}_init({sym}* s, void* bulk, {}float sample_rate);", cfg.decls);
    let _ =
        writeln!(h, "void {sym}_reset({sym}* s);   /* clears `poisoned`; no effect on an uninitialized instance */");
    if fns.params_default.is_some() {
        let _ = writeln!(h, "void {sym}_params_default({sym}_params* p);");
    }
    let io = process_io(cx, fns.process)?;
    let _ = writeln!(
        h,
        "/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */"
    );
    let _ = writeln!(h, "int  {sym}_process({sym}* s, const {sym}_params* p, {}uint32_t frames);", io.decls);
    if !meta.params.is_empty() {
        let _ = writeln!(h, "extern const onsa_param_info {sym}_param_info[{}];", meta.params.len());
    }
    if cx.opts.provides_alloc {
        let _ = writeln!(h, "\n/* Convenience on targets with a heap. */");
        let _ = writeln!(
            h,
            "{sym}* {sym}_new({}float sample_rate);   /* NULL when out of memory or `init` panicked */",
            cfg.decls
        );
        let _ = writeln!(h, "void {sym}_free({sym}* s);");
    }
    if cx.opts.panic == PanicMode::Poison {
        let _ = writeln!(
            h,
            "\n/* panic = \"poison\" (spec §9.2): a panic inside `process` zeroes the outputs, poisons the instance\n * (`process` returns 1 until `reset`); a panic inside an exported function returns a zero value and\n * {}take_panic() reports it once. */",
            cx.opts.prefix
        );
        let _ = writeln!(h, "int {}take_panic(void);", cx.opts.prefix);
    }
    let _ = writeln!(h, "\n#ifdef __cplusplus\n}}\n#endif");
    let _ = writeln!(h, "#endif /* {up}_H */");
    Ok(h)
}

struct ConfigArgs {
    /// `float time, ` (empty when the config has no fields)
    decls: String,
    /// `(name, field)` pairs
    fields: Vec<(String, String)>,
}

fn config_args(cx: &mut Cx, config: onsa_core::TypeId) -> R<ConfigArgs> {
    let fields = cx.fields(config).to_vec();
    let mut decls = String::new();
    let mut out = Vec::new();
    for (name, ty) in &fields {
        let tn = scalar_c(cx, ty, &format!("the `Init` input `{name}`"))?;
        let _ = write!(decls, "{tn} {}, ", ident(name));
        out.push((ident(name), ident(name)));
    }
    Ok(ConfigArgs { decls, fields: out })
}

fn scalar_c(cx: &mut Cx, ty: &Ty, what: &str) -> R<String> {
    if ty.is_scalar() {
        Ok(cx.names.name(ty))
    } else {
        Err(unsupported(no_span(), &format!("{what} of a non-scalar type in an export")))
    }
}

/// One `Span` / planar parameter of `process`.
struct IoParam {
    name: String,
    elem: Ty,
    /// `Some(n)`: `[Span[T]; n]` (planar channels)
    planar: Option<u32>,
    output: bool,
}

struct ProcessIo {
    decls: String,
    params: Vec<IoParam>,
}

fn process_io(cx: &mut Cx, process: FnId) -> R<ProcessIo> {
    let def = cx.m.fn_(process);
    let mut params = Vec::new();
    let mut decls = String::new();
    for p in def.params.iter().skip(2) {
        let name = ident(&def.locals[p.local.0 as usize].name);
        let output = matches!(p.mode, Mode::Inout);
        let (elem, planar) = match &p.ty {
            Ty::Span(e) => ((**e).clone(), None),
            Ty::Array(inner, n) => match &**inner {
                Ty::Span(e) => ((**e).clone(), Some(*n)),
                _ => return Err(unsupported(def.span, "this `process` parameter shape")),
            },
            _ => return Err(unsupported(def.span, "this `process` parameter shape")),
        };
        let et = scalar_c(cx, &elem, &format!("the signal `{name}`"))?;
        let c = if output { "" } else { "const " };
        match planar {
            None => {
                let _ = write!(decls, "{c}{et}* {name}, ");
            }
            Some(_) => {
                let _ = write!(decls, "{c}{et}* const* {name}, ");
            }
        }
        params.push(IoParam { name, elem, planar, output });
    }
    Ok(ProcessIo { decls, params })
}

/// The wrappers of one exported flow in the translation unit.
pub(crate) fn wrappers(cx: &mut Cx, e: &Export) -> R<String> {
    let meta = cx.m.flows[e.meta_index].clone();
    let fns = meta.fns.clone();
    let sym = e.symbol.clone();
    let state = cx.names.name(&Ty::Struct(fns.state));
    let config = cx.names.name(&Ty::Struct(fns.config));
    let params = cx.names.name(&Ty::Struct(fns.params));
    let has_bulk = cx.bulk.contains_key(&fns.state);
    let poisoned = cx
        .fields(fns.state)
        .iter()
        .find(|(n, _)| n == "poisoned")
        .map(|(n, _)| ident(n))
        .ok_or_else(|| crate::emit::internal("flow state without `poisoned`"))?;
    let initialized = cx
        .fields(fns.state)
        .iter()
        .find(|(n, _)| n == "initialized")
        .map(|(n, _)| ident(n))
        .ok_or_else(|| crate::emit::internal("flow state without `initialized`"))?;
    let mut s = String::new();
    let _ = writeln!(s, "/* ---- export: {} ---- */", meta.name);

    // init
    let cfg = config_args(cx, fns.config)?;
    let _ = writeln!(s, "int {sym}_init({sym}* s, void* bulk, {}float sample_rate) {{", cfg.decls);
    let _ = writeln!(s, "  {config} cfg;");
    let _ = writeln!(s, "  memset(&cfg, 0, sizeof cfg);");
    for (arg, field) in &cfg.fields {
        let _ = writeln!(s, "  cfg.{field} = {arg};");
    }
    if has_bulk {
        let _ = writeln!(s, "  s->bulk = bulk;");
    } else {
        let _ = writeln!(s, "  (void)bulk;");
    }
    if cx.opts.panic == PanicMode::Poison {
        // The state is being built, so the wrapper's own jmp_buf catches the panic (T4-4).
        // The previous slot is restored on every exit so that a wrapper entered from an
        // interrupt (or a nested host call) does not clear the outer wrapper's target (S-26).
        let _ = writeln!(s, "  jmp_buf onsa_jb;");
        let _ = writeln!(s, "  jmp_buf* onsa_prev = onsa_current_jmp;");
        // S-27: a panic inside `init` leaves the instance uninitialized: the whole
        // state (and the bulk region) is zeroed, `initialized` stays false, 1 is returned.
        let _ = writeln!(s, "  if (setjmp(onsa_jb)) {{");
        let _ = writeln!(s, "    onsa_current_jmp = onsa_prev;");
        if has_bulk {
            let bulk = cx.bulk[&fns.state].struct_name.clone();
            let _ = writeln!(s, "    if (bulk) memset(bulk, 0, sizeof({bulk}));");
        }
        let _ = writeln!(s, "    memset(s, 0, sizeof(*s));");
        if has_bulk {
            let _ = writeln!(s, "    s->bulk = bulk;");
        }
        let _ = writeln!(s, "    return 1;");
        let _ = writeln!(s, "  }}");
        let _ = writeln!(s, "  onsa_current_jmp = &onsa_jb;");
        let _ = writeln!(s, "  {}(s, &cfg, sample_rate);", cx.fn_name(fns.init));
        let _ = writeln!(s, "  onsa_current_jmp = onsa_prev;");
    } else {
        let _ = writeln!(s, "  {}(s, &cfg, sample_rate);", cx.fn_name(fns.init));
    }
    let _ = writeln!(s, "  return 0;");
    let _ = writeln!(s, "}}\n");

    // reset
    let _ =
        writeln!(s, "void {sym}_reset({sym}* s) {{ if (!s->{initialized}) return; {}(s); }}\n", cx.fn_name(fns.reset));

    // params_default
    if let Some(pd) = fns.params_default {
        let _ = writeln!(s, "void {sym}_params_default({sym}_params* p) {{ {}(p); }}\n", cx.fn_name(pd));
    }

    // process
    let io = process_io(cx, fns.process)?;
    let _ = writeln!(s, "int {sym}_process({sym}* s, const {sym}_params* p, {}uint32_t frames) {{", io.decls);
    let _ = writeln!(s, "  {params} q;");
    let _ = writeln!(s, "  if (!s->{initialized} || s->{poisoned}) return 1;");
    // Overlap checks (spec §14.2): every output against every input and every other output.
    let mut ranges: Vec<(String, bool)> = Vec::new(); // (pointer expr, is_output)
    for p in &io.params {
        match p.planar {
            None => ranges.push((p.name.clone(), p.output)),
            Some(n) => {
                for k in 0..n {
                    ranges.push((format!("{}[{k}]", p.name), p.output));
                }
            }
        }
    }
    for (i, (a, ao)) in ranges.iter().enumerate() {
        for (b, bo) in ranges.iter().skip(i + 1) {
            if !(ao | bo) {
                continue;
            }
            let et = io
                .params
                .iter()
                .find(|p| a.starts_with(&p.name))
                .map(|p| p.elem.clone())
                .unwrap_or(Ty::Float(onsa_core::FloatKind::F32));
            let etn = cx.names.name(&et);
            if *ao && *bo {
                let _ = writeln!(
                    s,
                    "  if ({a} == {b} || onsa_overlaps({a}, (size_t)frames * sizeof({etn}), {b}, (size_t)frames * sizeof({etn}))) return 2;"
                );
            } else {
                let _ = writeln!(
                    s,
                    "  if (onsa_overlaps({a}, (size_t)frames * sizeof({etn}), {b}, (size_t)frames * sizeof({etn}))) return 2;"
                );
            }
        }
    }
    let _ = writeln!(s, "  q = *p;");
    for (name, ty, pm) in &meta.params {
        let Some(pm) = pm else { continue };
        let (Some(min), Some(max)) = (pm.min, pm.max) else { continue };
        match ty {
            Ty::Float(onsa_core::FloatKind::F32) => {
                let _ = writeln!(
                    s,
                    "  q.{} = onsa_clamp_f32(q.{}, {}, {});",
                    ident(name),
                    ident(name),
                    f32_lit(min as f32),
                    f32_lit(max as f32)
                );
            }
            Ty::Float(onsa_core::FloatKind::F64) => {
                let _ = writeln!(
                    s,
                    "  q.{} = onsa_clamp_f64(q.{}, {}, {});",
                    ident(name),
                    ident(name),
                    crate::emit::f64_lit(min),
                    crate::emit::f64_lit(max)
                );
            }
            _ => {}
        }
    }
    if cx.opts.panic == PanicMode::Poison {
        // T4-4 (spec §9.2): a panic inside `process` lands here; the outputs
        // are zeroed and the instance is poisoned until `reset`. The jmp_buf
        // is the wrapper's own (S-26): the state layout stays host-independent.
        // The previous slot is restored on every exit so that a wrapper entered from an
        // interrupt (or a nested host call) does not clear the outer wrapper's target (S-26).
        let _ = writeln!(s, "  jmp_buf onsa_jb;");
        let _ = writeln!(s, "  jmp_buf* onsa_prev = onsa_current_jmp;");
        let _ = writeln!(s, "  if (setjmp(onsa_jb)) {{");
        let _ = writeln!(s, "    onsa_current_jmp = onsa_prev;");
        for p in &io.params {
            if !p.output {
                continue;
            }
            let et = cx.names.name(&p.elem);
            match p.planar {
                None => {
                    let _ = writeln!(s, "    memset({}, 0, (size_t)frames * sizeof({et}));", p.name);
                }
                Some(n) => {
                    let _ = writeln!(
                        s,
                        "    for (uint32_t onsa_k = 0; onsa_k < {n}; onsa_k++) memset({}[onsa_k], 0, (size_t)frames * sizeof({et}));",
                        p.name
                    );
                }
            }
        }
        let _ = writeln!(s, "    s->{poisoned} = true;");
        let _ = writeln!(s, "    return 1;");
        let _ = writeln!(s, "  }}");
        let _ = writeln!(s, "  onsa_current_jmp = &onsa_jb;");
    }
    let mut args = vec!["s".to_string(), "&q".to_string()];
    for p in &io.params {
        let tag = cx.names.tag(&p.elem);
        let cast = if p.output { String::new() } else { format!("({}*)", cx.names.name(&p.elem)) };
        match p.planar {
            None => args.push(format!("onsa_span_{tag}_of({cast}{}, frames)", p.name)),
            Some(n) => {
                let arr = cx.names.name(&Ty::Array(Box::new(Ty::Span(Box::new(p.elem.clone()))), n));
                let _ = writeln!(s, "  {arr} {}_spans;", p.name);
                for k in 0..n {
                    let _ =
                        writeln!(s, "  {}_spans.a[{k}] = onsa_span_{tag}_of({cast}{}[{k}], frames);", p.name, p.name);
                }
                // `[Span[T]; N]` parameters are aggregates: borrowed → `const T*`, `inout` → `T*`.
                args.push(format!("&{}_spans", p.name));
            }
        }
    }
    let _ = writeln!(s, "  {}({});", cx.fn_name(fns.process), args.join(", "));
    if cx.opts.panic == PanicMode::Poison {
        let _ = writeln!(s, "  onsa_current_jmp = onsa_prev;");
    }
    let _ = writeln!(s, "  return 0;");
    let _ = writeln!(s, "}}\n");

    // Parameter metadata table.
    if !meta.params.is_empty() {
        let _ = writeln!(s, "const onsa_param_info {sym}_param_info[{}] = {{", meta.params.len());
        for (name, _, pm) in &meta.params {
            let f = |v: Option<f64>| match v {
                Some(x) => f32_lit(x as f32),
                None => "NAN".into(),
            };
            let (min, max, def, step, unit, scale, label, id) = match pm {
                Some(pm) => (
                    f(pm.min),
                    f(pm.max),
                    f(pm.default),
                    f(pm.step),
                    pm.unit.clone().unwrap_or_default(),
                    pm.scale.clone().unwrap_or_else(|| "linear".into()),
                    pm.label.clone().unwrap_or_default(),
                    pm.id.clone().unwrap_or_else(|| name.clone()),
                ),
                None => (
                    "NAN".into(),
                    "NAN".into(),
                    "NAN".into(),
                    "NAN".into(),
                    String::new(),
                    "linear".into(),
                    String::new(),
                    name.clone(),
                ),
            };
            let _ = writeln!(
                s,
                "  {{ {}, {}, {min}, {max}, {def}, {step}, {}, {}, {} }},",
                crate::emit::c_string(name),
                crate::emit::c_string(&id),
                crate::emit::c_string(&unit),
                crate::emit::c_string(&scale),
                crate::emit::c_string(&label)
            );
        }
        let _ = writeln!(s, "}};\n");
    }

    // _new / _free
    if cx.opts.provides_alloc {
        let _ = writeln!(s, "{sym}* {sym}_new({}float sample_rate) {{", cfg.decls);
        let _ = writeln!(s, "  {sym}* s = ({sym}*)malloc(sizeof({state}));");
        let _ = writeln!(s, "  if (!s) return NULL;");
        if has_bulk {
            let bulk = cx.bulk[&fns.state].struct_name.clone();
            let _ = writeln!(s, "  {{ void* b = malloc(sizeof({bulk})); if (!b) {{ free(s); return NULL; }}");
            let args: Vec<String> = cfg.fields.iter().map(|(a, _)| a.clone()).collect();
            let _ = writeln!(
                s,
                "    if ({sym}_init(s, b, {}sample_rate) != 0) {{ free(b); free(s); return NULL; }} }}",
                args.iter().map(|a| format!("{a}, ")).collect::<String>()
            );
        } else {
            let args: Vec<String> = cfg.fields.iter().map(|(a, _)| a.clone()).collect();
            let _ = writeln!(
                s,
                "  if ({sym}_init(s, NULL, {}sample_rate) != 0) {{ free(s); return NULL; }}",
                args.iter().map(|a| format!("{a}, ")).collect::<String>()
            );
        }
        let _ = writeln!(s, "  return s;");
        let _ = writeln!(s, "}}\n");
        let _ = writeln!(s, "void {sym}_free({sym}* s) {{");
        let _ = writeln!(s, "  if (!s) return;");
        if has_bulk {
            let _ = writeln!(s, "  free(s->bulk);");
        }
        let _ = writeln!(s, "  free(s);");
        let _ = writeln!(s, "}}\n");
    }
    let _ = state;
    Ok(s)
}

/// Header of the exported plain functions (`[export] fns`).
pub(crate) fn fn_header(cx: &mut Cx, fns: &[FnId]) -> R<String> {
    let up: String = format!("{}{}", cx.opts.prefix, ident(&cx.opts.package)).to_ascii_uppercase();
    let mut h = String::new();
    let _ = writeln!(
        h,
        "/* exported functions of package `{}` — generated by onsa build; do not edit. */",
        cx.opts.package
    );
    let _ = writeln!(
        h,
        "#ifndef {up}_FNS_H\n#define {up}_FNS_H\n#include \"{}\"\n#ifdef __cplusplus\nextern \"C\" {{\n#endif\n",
        crate::RUNTIME_HEADER_NAME
    );
    for f in fns {
        let (proto, _) = fn_signature(cx, *f)?;
        let _ = writeln!(h, "{proto};");
    }
    if cx.opts.panic == PanicMode::Poison {
        let _ = writeln!(
            h,
            "\n/* panic = \"poison\" (spec §9.2): a panic inside an exported function makes it return a zero value;\n * {}take_panic() tells whether the last call panicked (and clears the flag). */",
            cx.opts.prefix
        );
        let _ = writeln!(h, "int {}take_panic(void);", cx.opts.prefix);
    }
    let _ = writeln!(h, "\n#ifdef __cplusplus\n}}\n#endif\n#endif");
    Ok(h)
}

/// `(prototype, argument forwarding)` of an exported function.
fn fn_signature(cx: &mut Cx, f: FnId) -> R<(String, Vec<String>)> {
    let def = cx.m.fn_(f);
    if def.sret || !(def.ret.is_scalar() || def.ret == Ty::Unit) {
        return Err(unsupported(def.span, "exporting a function that returns an aggregate"));
    }
    let short = def.name.rsplit('.').next().unwrap_or(&def.name).to_string();
    let sym = format!("{}{}", cx.opts.prefix, ident(&short));
    let ret = if def.ret == Ty::Unit { "void".to_string() } else { cx.names.name(&def.ret) };
    let mut decls = Vec::new();
    let mut fwd = Vec::new();
    for p in &def.params {
        let name = ident(&def.locals[p.local.0 as usize].name);
        match (&p.ty, p.mode) {
            (t, Mode::Inout) if t.is_scalar() => {
                decls.push(format!("{}* {name}", cx.names.name(t)));
                fwd.push(name);
            }
            (t, _) if t.is_scalar() => {
                decls.push(format!("{} {name}", cx.names.name(t)));
                fwd.push(name);
            }
            (Ty::Span(e), mode) if e.is_scalar() => {
                let et = cx.names.name(e);
                let tag = cx.names.tag(e);
                let c = if matches!(mode, Mode::Inout) { "" } else { "const " };
                decls.push(format!("{c}{et}* {name}, uint32_t {name}_len"));
                fwd.push(format!("onsa_span_{tag}_of(({et}*){name}, {name}_len)"));
            }
            _ => {
                return Err(unsupported(
                    def.span,
                    &format!(
                        "the parameter `{name}` of an exported function (only scalars and spans of scalars in this version)"
                    ),
                ));
            }
        }
    }
    let plist = if decls.is_empty() { "void".into() } else { decls.join(", ") };
    Ok((format!("{ret} {sym}({plist})"), fwd))
}

pub(crate) fn fn_wrapper(cx: &mut Cx, f: FnId) -> R<String> {
    let (proto, fwd) = fn_signature(cx, f)?;
    let def = cx.m.fn_(f);
    let inner = qualified(&def.name);
    let mut s = String::new();
    let _ = writeln!(s, "/* ---- export: {} ---- */", def.name);
    let _ = writeln!(s, "{proto} {{");
    if cx.opts.panic == PanicMode::Poison {
        // T4-4 (spec §9.2): panics do not cross the FFI boundary; the call
        // returns a zero value and `<prefix>take_panic()` reports it.
        let ret = if def.ret == Ty::Unit { None } else { Some(cx.names.name(&def.ret)) };
        // The previous slot is restored on every exit so that a wrapper entered from an
        // interrupt (or a nested host call) does not clear the outer wrapper's target (S-26).
        let _ = writeln!(s, "  jmp_buf onsa_jb;");
        let _ = writeln!(s, "  jmp_buf* onsa_prev = onsa_current_jmp;");
        match &ret {
            Some(r) => {
                let _ = writeln!(s, "  {r} onsa_r;");
                let _ = writeln!(
                    s,
                    "  if (setjmp(onsa_jb)) {{ onsa_current_jmp = onsa_prev; onsa_last_panic = 1; memset(&onsa_r, 0, sizeof onsa_r); return onsa_r; }}"
                );
            }
            None => {
                let _ = writeln!(
                    s,
                    "  if (setjmp(onsa_jb)) {{ onsa_current_jmp = onsa_prev; onsa_last_panic = 1; return; }}"
                );
            }
        }
        let _ = writeln!(s, "  onsa_current_jmp = &onsa_jb;");
        match &ret {
            Some(_) => {
                let _ = writeln!(s, "  onsa_r = {inner}({});", fwd.join(", "));
                let _ = writeln!(s, "  onsa_current_jmp = onsa_prev;");
                let _ = writeln!(s, "  return onsa_r;");
            }
            None => {
                let _ = writeln!(s, "  {inner}({});", fwd.join(", "));
                let _ = writeln!(s, "  onsa_current_jmp = onsa_prev;");
            }
        }
    } else if def.ret == Ty::Unit {
        let _ = writeln!(s, "  {inner}({});", fwd.join(", "));
    } else {
        let _ = writeln!(s, "  return {inner}({});", fwd.join(", "));
    }
    let _ = writeln!(s, "}}\n");
    Ok(s)
}

/// `<prefix>take_panic` and its flag (one per translation unit, T4-4).
pub(crate) fn take_panic(cx: &Cx) -> String {
    let mut s = String::new();
    let _ = writeln!(s, "/* ---- panic = \"poison\": the last exported function call panicked (spec §9.2) ---- */");
    let _ = writeln!(s, "static ONSA_THREAD_LOCAL int onsa_last_panic = 0;");
    let _ = writeln!(
        s,
        "int {}take_panic(void) {{ int p = onsa_last_panic; onsa_last_panic = 0; return p; }}\n",
        cx.opts.prefix
    );
    s
}
