//! The table of the rows (§18.1, S-250): one `Row` per form of the data file
//! `docs/foreign-forms.toml`, the rows a later work makes (`WAITING`), and the
//! rules (the notes) that several rows share.

use super::assign::{binary_minus_prefix_minus, compound_assignment, increment};
use super::calls::callee_expression;
use super::comments::block_comment;
use super::decls::{arm_return, endless_loop, hash_attribute, let_mut, proc, pub_crate};
use super::faust::faust_bit_not;
use super::literals::{foreign_literal, leading_point};
use super::modes::{mut_self, reference};
use super::paths::{angle_brackets, path_separator, space_in_type_args_mark, type_args_call, type_position_path};
use super::ranges::{range_dots, range_header_one_sided, range_outside_header};
use super::semicolons::{semicolon, semicolon_in_list};
use super::*;

const NO_REFERENCES: &str =
    "there are no references: an argument is borrowed by default and changed with `inout` before it (§5.2)";

const SEMICOLON_RULE: &str = "a statement or declaration ends at the end of its line; there is no `;` (§2.5)";

const FLOAT_LITERAL_RULE: &str = "a float literal with a point has digits on both sides of it (`1.0`, `0.5`, §2.4)";

const SPACE_BEFORE_OPEN_RULE: &str = "a postfix `(` or `[` that opens a list (the arguments of a call, an index, type arguments, the parameters of a declaration, a pattern, an attribute) is written right after the token before it, with no blank or line break between them (`f(x)`, `xs[0]`, §2.5)";

const BLOCK_COMMENT_RULE: &str =
    "comments are line comments `//`, to the end of the line; `///` documents the next declaration (§2.1)";

/// The rule of the forms of type arguments in an expression (the note, §4.5).
const TYPE_ARGS_RULE: &str = "a type argument in an expression is written after the name, `name::[T]` (`id::[U8](250)`); a `[` alone is an index (§4.5)";

pub static ROWS: &[Row] = &[
    Row {
        id: RowId::ArmReturn,
        name: "arm_return",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`return`, `break` and `continue` are statements; an arm that is one is written as a block",
        rule: "`return`, `break` and `continue` are statements, written in a block: `None => { return 0 },` (§7)",
        detect: Detect::Syntax(arm_return),
    },
    Row {
        id: RowId::SpaceBeforeQuestion,
        name: "space_before_question",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a postfix `?` is written right after its operand",
        rule: "the postfix `?` is written right after its operand, with no blank or line break before it (`x?`); `x ?` reads as the start of the conditional operator of C (§2.5)",
        detect: Detect::Syntax(spaces::space_before_question),
    },
    Row {
        id: RowId::SpaceAfterPrefix,
        name: "space_after_prefix",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a prefix operator is written right before its operand",
        rule: "the prefix `-` and `!` are written right before their operand, with no blank or line break (`-x`, `!done`, the pattern `-1`, §2.5)",
        detect: Detect::Syntax(spaces::space_after_prefix),
    },
    Row {
        id: RowId::SpaceAfterCaret,
        name: "space_after_caret",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "the mark `^` is written right before the name",
        rule: "the mark `^` of a feedback reference is written right before the name, `^y`; `^ y` reads as the binary exclusive or (§2.5, §2.6)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::AsymmetricBinarySpace,
        name: "asymmetric_binary_space",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a binary operator with a blank only before it reads as the prefix of the next element too",
        rule: "a binary `-`, `^` or `+` has blanks on both sides or on none (`a - b`); `a -b` reads as `a` and `-b` too (§2.5)",
        detect: Detect::Syntax(spaces::asymmetric_binary_space),
    },
    Row {
        id: RowId::LeadingOperator,
        name: "leading_operator",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a line does not start with an operator that goes on with the line before",
        rule: "a binary operator, the `|` of a pattern choice, a `->` and a `=` go at the end of the line, not at the head of the next: a line ends at its end, in brackets too (§2.5)",
        detect: Detect::Syntax(lines::leading_symbol),
    },
    Row {
        id: RowId::LeadingMinus,
        name: "leading_minus",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a line that starts with a `-` or `^` reads as a new line with a prefix",
        rule: "a binary `-` or `^` goes at the end of the line; a prefix one touches its operand (`-b`, §2.5)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::LeadingRange,
        name: "leading_range",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a line does not start with a range symbol",
        rule: "a range symbol (`..<`, `..=`) goes at the end of the line, as a binary operator does (§2.5)",
        detect: Detect::Syntax(ranges::leading_range),
    },
    Row {
        id: RowId::LeadingVert,
        name: "leading_vert",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a `|` goes between the alternatives of a pattern, not before the first",
        rule: "the `|` of a pattern choice is written between its alternatives only; arms are separated by `,` (§7)",
        detect: Detect::Syntax(lines::leading_vert),
    },
    Row {
        id: RowId::PatternDoubleVert,
        name: "pattern_double_vert",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "the alternatives of a pattern are separated by one `|`",
        rule: "a pattern choice is `p | q`; `||` is the logical or of expressions (§7)",
        detect: Detect::Syntax(lines::pattern_double_vert),
    },
    Row {
        id: RowId::PrefixPlus,
        name: "prefix_plus",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "there is no prefix `+`",
        rule: "Onsa has no prefix `+`: a number or an operand is written without it (§3.1)",
        detect: Detect::Syntax(lines::prefix_plus),
    },
    Row {
        id: RowId::NewlineAfterDot,
        name: "newline_after_dot",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a member `.` is written at the head of the line of its member",
        rule: "no line break goes after a member `.`, also in a list; a chain goes on with the `.` at the head of the next line (§2.5)",
        detect: Detect::Syntax(lines::newline_after_dot),
    },
    Row {
        id: RowId::NewlineAfterPrefix,
        name: "newline_after_prefix",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a prefix symbol is written on the line of its operand",
        rule: "the prefix `-`, `!` and `^` are written on the line of their operand, also in a list (§2.5)",
        detect: Detect::Syntax(lines::newline_after_prefix),
    },
    Row {
        id: RowId::NewlineBeforeQuestion,
        name: "newline_before_question",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a postfix `?` is written on the line of its operand",
        rule: "the postfix `?` is written right after its operand, with no line break before it, also in a list (§2.5)",
        detect: Detect::Syntax(lines::newline_before_question),
    },
    Row {
        id: RowId::Semicolon,
        name: "semicolon",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`;` is not used in Onsa; a statement or declaration ends at the end of its line",
        rule: SEMICOLON_RULE,
        detect: Detect::Syntax(semicolon),
    },
    Row {
        id: RowId::SemicolonInList,
        name: "semicolon_in_list",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "the elements of a list are separated with `,`",
        rule: "the elements of a list (fields, arguments, parameters, ...) are separated with `,`; there is no `;` (§2.5)",
        detect: Detect::Syntax(semicolon_in_list),
    },
    Row {
        id: RowId::PathSeparator,
        name: "path_separator",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "paths are separated with `.`",
        rule: "the separator of a path is `.` (`F32.PI`, `std.math`, §15.1)",
        detect: Detect::Syntax(path_separator),
    },
    Row {
        id: RowId::AngleBrackets,
        name: "angle_brackets",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "type parameters and type arguments are written in `[ ]`",
        rule: "type parameters and type arguments are written in `[ ]` (§4.5)",
        detect: Detect::Syntax(angle_brackets),
    },
    Row {
        id: RowId::RefMutParam,
        name: "ref_mut_param",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`&mut T` is written `inout name: T`; the mode comes before the name",
        rule: NO_REFERENCES,
        detect: Detect::Syntax(reference),
    },
    Row {
        id: RowId::RefMutSelf,
        name: "ref_mut_self",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a receiver that changes is written `inout self`",
        rule: "the mode comes before the name; a receiver that changes is `inout self` (§5.2)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::MutSelf,
        name: "mut_self",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a receiver the method takes is written `move self`",
        rule: "the mode comes before the name: `self` borrows, `inout self` changes the caller's value, `move self` takes it (§5.2)",
        detect: Detect::Syntax(mut_self),
    },
    Row {
        id: RowId::RefSelf,
        name: "ref_self",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`&self` is the default borrow; write `self`",
        rule: "the mode comes before the name; `self` is borrowed by default (§5.2)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RefType,
        name: "ref_type",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`&T` is the default borrow; write the type without `&`",
        rule: NO_REFERENCES,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RefExpr,
        name: "ref_expr",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "there are no references; a value is borrowed by default",
        rule: NO_REFERENCES,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RefMutArg,
        name: "ref_mut_arg",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "an argument that changes is written `inout x`",
        rule: NO_REFERENCES,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RefMutOther,
        name: "ref_mut_other",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "there are no mutable references; only a parameter or an argument changes a value it borrows, with `inout`",
        rule: NO_REFERENCES,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::LowercaseType,
        name: "lowercase_type",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "built-in types are written in UpperCamel (`I32`, `F32`, `Bool`)",
        rule: "type names are UpperCamel, the built-in ones too (`I32`, `F32`, `Bool`, `Char`, `Str`, §2.3)",
        detect: Detect::TypeName,
    },
    Row {
        id: RowId::CompoundAssign,
        name: "compound_assign",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "there is no compound assignment; write the operation out",
        rule: "an assignment is `place = value`; the operation is written out, `x = x + 1` (§5.1)",
        detect: Detect::Syntax(compound_assignment),
    },
    Row {
        id: RowId::CompoundAssignUnfixable,
        name: "compound_assign_unfixable",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "there is no compound assignment, and this one cannot be written out as it stands",
        rule: "an assignment is `place = value`; the operation is written out, `x = x + 1` (§5.1)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::BinaryMinusPrefixMinus,
        name: "binary_minus_prefix_minus",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a binary `-` and a prefix `-` are written apart, not as `--`",
        rule: "a prefix `-` after a binary `-` is written with a blank between them, `a - -b` (§2.5)",
        detect: Detect::Syntax(binary_minus_prefix_minus),
    },
    Row {
        id: RowId::Increment,
        name: "increment",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "there is no `++` or `--`; write the assignment out",
        rule: "there is no increment; a statement `x = x + 1` writes it out (§5.1)",
        detect: Detect::Syntax(increment),
    },
    Row {
        id: RowId::IncrementUnfixable,
        name: "increment_unfixable",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "there is no `++` or `--`, and an assignment is a statement, not an expression",
        rule: "there is no increment; a statement `x = x + 1` writes it out (§5.1)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::LetMut,
        name: "let_mut",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a local that changes is declared with `var`",
        rule: "`let` binds a value that does not change; a local that changes is declared with `var` (§5.1)",
        detect: Detect::Syntax(let_mut),
    },
    Row {
        id: RowId::Loop,
        name: "loop",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "there is no `loop`; an endless loop is `while true`",
        rule: "the loops are `while` and `for`; an endless loop is `while true` (§7)",
        detect: Detect::Syntax(endless_loop),
    },
    Row {
        id: RowId::Proc,
        name: "proc",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a signal-processing node is declared with `flow`",
        rule: "a stateful signal-processing node is declared with `flow` (§11)",
        detect: Detect::Syntax(proc),
    },
    Row {
        id: RowId::FloatTrailingDot,
        name: "float_trailing_dot",
        phase: Phase::Lexical,
        code: Code::E0020,
        message: "a float literal needs digits on both sides of the point",
        rule: FLOAT_LITERAL_RULE,
        detect: Detect::Syntax(foreign_literal),
    },
    Row {
        id: RowId::FloatLeadingDot,
        name: "float_leading_dot",
        phase: Phase::Lexical,
        code: Code::E0020,
        message: "a float literal needs digits on both sides of the point",
        rule: FLOAT_LITERAL_RULE,
        detect: Detect::Syntax(leading_point),
    },
    Row {
        id: RowId::LiteralSuffix,
        name: "literal_suffix",
        phase: Phase::Lexical,
        code: Code::E0020,
        message: "literals have no type suffix; the type comes from the context",
        rule: "a literal has no type suffix; its type comes from the context or an annotation (§2.4)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::BlockComment,
        name: "block_comment",
        phase: Phase::Lexical,
        code: Code::E0020,
        message: "Onsa has no block comments; comments are line comments `//`",
        rule: BLOCK_COMMENT_RULE,
        detect: Detect::Syntax(block_comment),
    },
    Row {
        id: RowId::BlockCommentUnclosed,
        name: "block_comment_unclosed",
        phase: Phase::Lexical,
        code: Code::E0002,
        message: "Onsa has no block comments, and this one is never closed",
        rule: BLOCK_COMMENT_RULE,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::BlockCommentNested,
        name: "block_comment_nested",
        phase: Phase::Lexical,
        code: Code::E0002,
        message: "Onsa has no block comments, and this one holds another",
        rule: BLOCK_COMMENT_RULE,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::BlockCommentMultilineCodeAfter,
        name: "block_comment_multiline_code_after",
        phase: Phase::Lexical,
        code: Code::E0002,
        message: "Onsa has no block comments, and code follows this one on the line it ends",
        rule: BLOCK_COMMENT_RULE,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::FloatPattern,
        name: "float_pattern",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "float literals cannot be patterns; compare in a guard",
        rule: "a pattern holds no float literal; IEEE equality is written in a guard, `x if x == 1.0` (§7)",
        detect: Detect::Syntax(guard_pattern),
    },
    Row {
        id: RowId::FloatPatternChoice,
        name: "float_pattern_choice",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "float literals cannot be patterns, and these alternatives do not merge into one guard",
        rule: "a pattern holds no float literal; alternatives of other shapes are split into arms, or written in a guard (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::InterpolatedStringPattern,
        name: "interpolated_string_pattern",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a string with an interpolation cannot be a pattern; compare in a guard",
        rule: "a string with an interpolation makes a value and is no pattern; it is compared in a guard, `v if v == \"a{x}b\"` (a string of `{{` and `}}` only has none); alternatives of other shapes are split into arms (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::NegatedConstantPattern,
        name: "negated_constant_pattern",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a constant with `-` cannot be a pattern; compare in a guard",
        rule: "the `-` of a pattern is on an integer literal; a negated constant is compared in a guard, `x if x == -LIMIT`; alternatives of other shapes are split into arms (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::AtBinding,
        name: "at_binding",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "Onsa has no `@` bindings; compare in a guard",
        rule: "there is no `@` binding: the name is bound and its value compared in a guard, `n @ 1..<5` is `n if 1 <= n && n < 5`, `k @ LIMIT` is `k if k == LIMIT` (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::AtBindingComplex,
        name: "at_binding_complex",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "Onsa has no `@` bindings, and this one is no comparison a guard can write",
        rule: "there is no `@` binding; when its right side is not literals, constants and ranges (and their choice in parentheses), it is written with a guard or a nested `match`; `@` binds more strongly than `|`, and the `|` of a pattern is a choice: a bitwise or in an end is written in parentheses (`1..<(5 | 7)`) (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RangePattern,
        name: "range_pattern",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "ranges cannot be patterns; compare in a guard",
        rule: "a range is written only in the header of a `for` or a `par`; in a pattern it is compared in a guard, `1..<3` is `k if 1 <= k && k < 3` (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RangePatternChoice,
        name: "range_pattern_choice",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "ranges cannot be patterns, and these alternatives do not merge into one guard",
        rule: "a range is no pattern; alternatives of other shapes are split into arms, or written in a guard; the `|` of a pattern is a choice: a bitwise or in an end is written in parentheses (`1..<(5 | 7)`) (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::HashAttribute,
        name: "hash_attribute",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "attributes are written `@name(...)`",
        rule: "an attribute is written `@name(...)` (§6.5)",
        detect: Detect::Syntax(hash_attribute),
    },
    Row {
        id: RowId::FaustBitNot,
        name: "faust_bit_not",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "bits are negated with the prefix `!`",
        rule: "the bitwise negation is the prefix `!` (§2.6); a prefix `~` reads as the feedback of FAUST",
        detect: Detect::Syntax(faust_bit_not),
    },
    Row {
        id: RowId::PubCrate,
        name: "pub_crate",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`pub(crate)` is visibility within the package, which is the default; remove it",
        rule: "visibility is `pub` (outside the package), nothing (the package), or `priv` (§15.1)",
        detect: Detect::Syntax(pub_crate),
    },
    Row {
        id: RowId::TypeArgsTurbofish,
        name: "type_args_turbofish",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "type arguments in an expression are written `name::[…]`, in `[ ]`",
        rule: TYPE_ARGS_RULE,
        detect: Detect::Syntax(type_args_call),
    },
    Row {
        id: RowId::TypeArgsAngle,
        name: "type_args_angle",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "type arguments of a call are written `name::[…]`, not in `< >`",
        rule: TYPE_ARGS_RULE,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::TypeArgsSquareComma,
        name: "type_args_square_comma",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "type arguments in an expression are written `name::[…]`; a `[…]` with `,` is no index",
        rule: TYPE_ARGS_RULE,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::TypeArgsOnExpression,
        name: "type_args_on_expression",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a function value takes no type arguments; it is called with `.(`",
        rule: "a function value is called with `.(` (§6.1); type arguments go after the name of an item, `name::[T]` (§4.5)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::TypePositionPath,
        name: "type_position_path",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a type writes its arguments in `[ ]` without `::`",
        rule: "in a type the arguments follow the name, `Buf[F32]`; `name::[…]` is written only in an expression, where a `[` alone is an index (§4.5)",
        detect: Detect::Syntax(type_position_path),
    },
    Row {
        id: RowId::SpaceInTypeArgsMark,
        name: "space_in_type_args_mark",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`::[` is written without spaces",
        rule: "type arguments in an expression are written `name::[T]`, with no space before or after the `::` (§2.5, §4.5)",
        detect: Detect::Syntax(space_in_type_args_mark),
    },
    Row {
        id: RowId::RangeDots,
        name: "range_dots",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a range is written `a..<b` (without its end) or `a..=b` (with it)",
        rule: "a range `a..<b` excludes `b` and `a..=b` includes it; `..` and `...` include the end in some languages and not in others (§7)",
        detect: Detect::Syntax(range_dots),
    },
    Row {
        id: RowId::StructPatternRest,
        name: "struct_pattern_rest",
        phase: Phase::Types,
        code: Code::E0020,
        message: "a struct pattern names every field; Onsa has no `..`",
        rule: "a struct pattern names every field once, the unused ones `_`, so that a field added later makes every pattern of the struct an error (§7)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::RangeHeaderOneSided,
        name: "range_header_one_sided",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "a range in the head of a `for` or a `par` has both ends",
        rule: "a loop over a range writes both of its ends, `0..<n` or `0..=n`; a range with one end is no head (§7)",
        detect: Detect::Syntax(range_header_one_sided),
    },
    Row {
        id: RowId::RangeOutsideHeader,
        name: "range_outside_header",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "ranges are only written in `for` and `par` heads",
        rule: "a range is the whole head of a `for` or a `par` and is not a value (§7); a part of a sequence is `xs.slice(from, to)` (§5.3)",
        detect: Detect::Syntax(range_outside_header),
    },
    Row {
        id: RowId::SpaceAroundDot,
        name: "space_around_dot",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a member `.` is written without spaces around it",
        rule: "the member `.` (a field, a method, a tuple index, the `.(` of a function value) takes no space on either side inside a line: `a.b`, `s.f.(x)`; a `.` that starts the next line continues the expression (§2.5)",
        detect: Detect::Syntax(spaces::space_around_dot),
    },
    Row {
        id: RowId::SpaceBeforeParen,
        name: "space_before_paren",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a `(` that opens a list is written right after the token before it",
        rule: SPACE_BEFORE_OPEN_RULE,
        detect: Detect::Syntax(spaces::space_before_open),
    },
    Row {
        id: RowId::SpaceBeforeBracket,
        name: "space_before_bracket",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a `[` that opens a list is written right after the token before it",
        rule: SPACE_BEFORE_OPEN_RULE,
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::SpaceBeforeBang,
        name: "space_before_bang",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "the `!` of a call that changes its receiver is written right after the name",
        rule: "a name and its mark `!` are written without a blank between them, and the `(` right after the mark (`buf.push!(x)`, §2.5, §2.6)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::SpaceBeforeTilde,
        name: "space_before_tilde",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "the `~` of a flow call is written right after the name",
        rule: "a name and its mark `~` are written without a blank between them, and the `(` right after the mark (`saw~(f0)`); `saw ~(f0)` reads as the binary `~` of FAUST (§2.5, §2.6)",
        detect: Detect::Syntax(no_match),
    },
    Row {
        id: RowId::StringPrefix,
        name: "string_prefix",
        phase: Phase::Syntax,
        code: Code::E0002,
        message: "a string or character literal has no prefix or suffix",
        rule: "a string is written `\"…\"` in UTF-8, with the interpolation `\"{x}\"`, and a byte string is `\"x\".as_bytes()`; no name is written right before or after a literal (§2.4)",
        detect: Detect::Syntax(spaces::string_prefix),
    },
    Row {
        id: RowId::CalleeExpression,
        name: "callee_expression",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a callee that is no path of names is a function value; it is called with `.(`",
        rule: "a function value is called with `.(` (`s.f.(x)`, `pick(true).(5)`); `f(x)` calls an item, whose callee is a path of names (§6.1)",
        detect: Detect::Syntax(callee_expression),
    },
    Row {
        id: RowId::SpaceAfterBranchKeyword,
        name: "space_after_branch_keyword",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "`if~` and `match~` are written with no blank between the keyword and `~`",
        rule: "`if~` / `match~` evaluate every branch; the `~` touches the `if` or `match` (§2.6). A prefix `~` is no operator: the bitwise negation is `!`",
        detect: Detect::Syntax(flow::space_after_branch_keyword),
    },
    Row {
        id: RowId::ElseIfTilde,
        name: "else_if_tilde",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "the `~` of a chain of `if` is written on its first `if` only",
        rule: "the `~` of `if~` stands for the whole chain of `else if` (`if~ c { a } else if d { b } else { e }`), and is written on the first `if` (§11.5)",
        detect: Detect::Syntax(flow::else_if_tilde),
    },
    Row {
        id: RowId::ClockOnBinding,
        name: "clock_on_binding",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a clock is written on the value, not on the binding",
        rule: "a clock is written on an expression (`let y: F32 = x at sample`) or after the type of an input or output of a flow, never on the type of a binding (§11.3)",
        detect: Detect::Tree,
    },
    Row {
        id: RowId::ClockInType,
        name: "clock_in_type",
        phase: Phase::Syntax,
        code: Code::E0020,
        message: "a clock is no part of a type",
        rule: "a clock is written after the type of an input or output of a flow (`x: F32 at sample`) or on an expression (`p at sample`); the type of a value is a plain type everywhere (§11.3)",
        detect: Detect::Tree,
    },
];

/// The rows of the data file that no work has made yet (the later works
/// of W3 to W7; [`Waiting`]).
pub static WAITING: &[Waiting] = &[
    Waiting { name: "octal_prefix", phase: Phase::Lexical, code: Code::E0020 },
    Waiting { name: "leading_zero", phase: Phase::Lexical, code: Code::E0020 },
    Waiting { name: "float_dot_exponent", phase: Phase::Lexical, code: Code::E0020 },
    Waiting { name: "value_call", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "item_dot_call", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "indexed_value_call", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "field_call", phase: Phase::Types, code: Code::E0020 },
    Waiting { name: "float_constant_pattern", phase: Phase::Types, code: Code::E0020 },
    Waiting { name: "type_args_square", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "type_args_method_square", phase: Phase::Types, code: Code::E0020 },
    Waiting { name: "rate_as_type", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "caret_visible", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "faust_feedback", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "faust_feedback_unnamed", phase: Phase::Syntax, code: Code::E0002 },
    Waiting { name: "faust_prime", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "faust_delay", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "faust_delay_variable", phase: Phase::Syntax, code: Code::E0002 },
    Waiting { name: "faust_compose", phase: Phase::Syntax, code: Code::E0002 },
    Waiting { name: "derive_attribute", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "relaxed_attribute", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "bulk_attribute", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "mem_fast", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "field_pub", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "field_priv_in_priv_struct", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "pub_pkg", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "priv_use", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "tuple_struct", phase: Phase::Syntax, code: Code::E0020 },
    Waiting { name: "copy_impl", phase: Phase::Names, code: Code::E0020 },
    Waiting { name: "copy_bound", phase: Phase::Names, code: Code::E0020 },
];
