//! Definitions: every named item of every module, in one arena (`DefId`).
//! Signatures are lowered here (T2-2); bodies are checked by T2-5 onwards.

use onsa_diag::Span;
use onsa_syntax::ast::{ExprId, ItemId, Mode, Vis};

use crate::ty::{EffectSet, Rate, TyId};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct DefId(pub u32);

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct ModId(pub u32);

/// Builtin trait names usable as bounds (§6.3). User traits are phase 2.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Bound {
    Num,
    Float,
    PartialEq,
    PartialOrd,
    Eq,
    Ord,
    Copy,
    Dup,
    Hash,
    Show,
    Default,
}

impl Bound {
    pub fn parse(s: &str) -> Option<Bound> {
        Some(match s {
            "Num" => Bound::Num,
            "Float" => Bound::Float,
            "PartialEq" => Bound::PartialEq,
            "PartialOrd" => Bound::PartialOrd,
            "Eq" => Bound::Eq,
            "Ord" => Bound::Ord,
            "Copy" => Bound::Copy,
            "Dup" => Bound::Dup,
            "Hash" => Bound::Hash,
            "Show" => Bound::Show,
            "Default" => Bound::Default,
            _ => return None,
        })
    }
}

#[derive(Debug, Clone)]
pub enum GenericKind {
    /// `T`, `T: Num`, `T: ?Dup` (`dup == false` lifts the implicit `Dup` bound, §4.5).
    Type { bounds: Vec<Bound>, dup: bool },
    /// `const N: U32`
    Const(TyId),
    /// `e` (effect-row variable)
    Effect,
}

#[derive(Debug, Clone)]
pub struct GenericDef {
    pub name: String,
    pub span: Span,
    pub kind: GenericKind,
}

#[derive(Debug, Clone)]
pub struct ParamSig {
    pub name: String,
    pub mode: Mode,
    pub ty: TyId,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct FnDef {
    pub generics: Vec<GenericDef>,
    /// `self` receiver mode, for methods.
    pub self_mode: Option<Mode>,
    pub params: Vec<ParamSig>,
    pub ret: TyId,
    pub rt: bool,
    pub effects: EffectSet,
    /// `None` for `target` declarations and generated flow functions.
    pub body: Option<ExprId>,
    /// `target fn`: the backend provides the body (§15.2, D-07).
    pub target: bool,
    /// Generated by a flow (§11.6); which one.
    pub flow_fn: Option<FlowFn>,
}

/// Functions generated for a flow (§11.6).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlowFn {
    Init,
    Reset,
    Process,
    ProcessInplace,
    Render,
    ParamsDefault,
}

#[derive(Debug, Clone)]
pub struct FieldDef {
    pub name: String,
    pub ty: TyId,
    pub vis: Vis,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub enum Fields {
    Named(Vec<FieldDef>),
    /// `struct Hz(F32)`
    Tuple(TyId),
    /// `target type` / `extern` opaque types, and flow `State` until M3.
    Opaque,
}

/// `@derive` traits (S-13: `Hash` / `Show` are E0200 in phase 1).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Derive {
    PartialEq,
    Eq,
    PartialOrd,
    Ord,
    Default,
}

#[derive(Debug, Clone)]
pub struct StructDef {
    pub generics: Vec<GenericDef>,
    pub fields: Fields,
    pub derives: Vec<Derive>,
    /// Generated by a flow (§11.6): which type.
    pub flow_ty: Option<FlowTy>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FlowTy {
    State,
    Config,
    Params,
    Out,
}

#[derive(Debug, Clone)]
pub struct VariantDef {
    pub name: String,
    pub fields: Vec<TyId>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct EnumDef {
    pub generics: Vec<GenericDef>,
    pub variants: Vec<VariantDef>,
    pub derives: Vec<Derive>,
}

#[derive(Debug, Clone)]
pub struct ConstDef {
    pub ty: TyId,
    /// `None` inside a `trait`, and for generated `SIZE` / `BULK_SIZE` (M3).
    pub value: Option<ExprId>,
    /// The value when the initializer is an integer literal (array lengths, §4.1).
    pub int_value: Option<u64>,
}

#[derive(Debug, Clone)]
pub struct ImplDef {
    pub generics: Vec<GenericDef>,
    pub self_ty: TyId,
    /// Methods and associated functions, in order.
    pub fns: Vec<DefId>,
    pub consts: Vec<DefId>,
}

/// `@param(...)` metadata (§11.7). Numeric values are evaluated from literals.
#[derive(Debug, Clone)]
pub struct ParamMeta {
    pub min: Option<f64>,
    pub max: Option<f64>,
    pub default: Option<f64>,
    pub step: Option<f64>,
    pub unit: Option<String>,
    pub scale: Option<String>,
    pub label: Option<String>,
    pub id: Option<String>,
    pub span: Span,
}

impl ParamMeta {
    pub fn empty(span: Span) -> ParamMeta {
        ParamMeta {
            min: None,
            max: None,
            default: None,
            step: None,
            unit: None,
            scale: None,
            label: None,
            id: None,
            span,
        }
    }
}

#[derive(Debug, Clone)]
pub struct FlowInput {
    pub name: String,
    pub rate: Rate,
    /// Value type (without the rate).
    pub ty: TyId,
    pub param: Option<ParamMeta>,
    pub span: Span,
}

#[derive(Debug, Clone)]
pub struct FlowDef {
    pub inputs: Vec<FlowInput>,
    /// Output value type (rate is always `Sig`, §11.6).
    pub out: TyId,
    pub body: ExprId,
    /// Generated namespace items (§11.6): `State`, `Config`, ..., `process`, ...
    pub members: Vec<(String, DefId)>,
}

#[derive(Debug, Clone)]
pub enum DefKind {
    Fn(FnDef),
    Flow(FlowDef),
    Struct(StructDef),
    Enum(EnumDef),
    /// `type A = B`, expanded.
    Alias(TyId),
    Const(ConstDef),
    Impl(ImplDef),
    /// `test "name" { }`
    Test {
        name: String,
        body: ExprId,
    },
    /// A declaration phase 1 does not support (E0200 reported); kept so that
    /// names resolve without cascading errors.
    Unsupported,
}

#[derive(Debug, Clone)]
pub struct Def {
    pub name: String,
    pub module: ModId,
    pub vis: Vis,
    pub span: Span,
    /// Span of the name, for diagnostics.
    pub name_span: Span,
    pub kind: DefKind,
    /// The AST item, when the def comes from source.
    pub item: Option<ItemId>,
    /// `impl` block or flow that owns this def.
    pub owner: Option<DefId>,
}

impl Def {
    pub fn as_fn(&self) -> Option<&FnDef> {
        match &self.kind {
            DefKind::Fn(f) => Some(f),
            _ => None,
        }
    }

    pub fn as_struct(&self) -> Option<&StructDef> {
        match &self.kind {
            DefKind::Struct(s) => Some(s),
            _ => None,
        }
    }

    pub fn as_enum(&self) -> Option<&EnumDef> {
        match &self.kind {
            DefKind::Enum(e) => Some(e),
            _ => None,
        }
    }

    pub fn as_flow(&self) -> Option<&FlowDef> {
        match &self.kind {
            DefKind::Flow(f) => Some(f),
            _ => None,
        }
    }

    /// Generic parameters of the def itself (not of its owner).
    pub fn generics(&self) -> &[GenericDef] {
        match &self.kind {
            DefKind::Fn(f) => &f.generics,
            DefKind::Struct(s) => &s.generics,
            DefKind::Enum(e) => &e.generics,
            DefKind::Impl(i) => &i.generics,
            _ => &[],
        }
    }
}
