[package]
name = "onsa_driver"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
onsa_diag.workspace = true
onsa_syntax.workspace = true
onsa_sema.workspace = true
onsa_core.workspace = true
onsa_interp.workspace = true
onsa_backend_c.workspace = true
onsa_backend_wasm.workspace = true
onsa_backend_js.workspace = true
serde_json.workspace = true

[lints]
workspace = true
