#!/usr/bin/env python3
"""Generate and check the test vectors of spec 3.3 / 3.4 (W2-01, Q-02 (a), R-133).

    tools/vectors/gen.py --out tests/vectors       write the data and the fixture
    tools/vectors/gen.py --check                   the gate item `vectors`
    tools/vectors/gen.py --explain FILE:LINE       a row in words

The reference model (model.py) is the only place that computes an expected value; the
spec and the data are the norm, not this program. The data is rebuilt byte for byte.
`--check` regenerates in memory and compares with tests/vectors/ (every file), runs the
known-answer tests of the model, compares the registry with the spec's operation tokens,
checks that every operation has an `edge` section and every named case is in the data,
and that `XCHECK` was written for this data (the cross-check was run after the last
change; tools/vectors/xcheck.py runs it).
"""
import argparse
import hashlib
import sys
import time
import traceback
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import model as M  # noqa: E402
import named  # noqa: E402
import ops as O  # noqa: E402
import sets as S  # noqa: E402
import spec_tokens  # noqa: E402

ROOT = HERE.parent.parent
DATA = ROOT / "tests" / "vectors"
SPEC = ROOT / "onsa-lang-spec-0.3.md"
FORMAT_VERSION = 1
HAND_WRITTEN = {"FORMAT.md", "XCHECK"}   # in tests/vectors/, not generated
PREAMBLE = "# Onsa test vectors, format 1 (tests/vectors/FORMAT.md). Generated by tools/vectors/gen.py: do not edit."
TIER_ORDER = ("edge", "rand")


def sha(b):
    return hashlib.sha256(b).hexdigest()


# ---------------------------------------------------------------- the data
def build_sections(ops):
    """{op id: {tier: [(args text, expected text, note)]}} in a fixed order, and the held counts."""
    by_id = {o.id: o for o in ops}
    notes = {}
    forced = {}
    for op_id, args, note in named.named_cases(by_id):
        notes[(op_id, args)] = note
        forced.setdefault(op_id, []).append(args)
    sections = {}
    for o in ops:
        rows = o.inputs()
        have = {a for _, a in rows}
        for args in forced.get(o.id, []):
            if args not in have:
                rows.append(("edge", args))
                have.add(args)
        tiers = {}
        for tier, args in rows:
            r, holds = M.decide(o.model, args)
            note = [notes[(o.id, args)]] if (o.id, args) in notes else []
            if holds:
                tier, expect = "held-" + "+".join(holds), "?"
                note += [h[0] + "-" + h[1:] for h in holds]   # S207 -> S-207: the held rows are found by the decision's number
            else:
                expect = O.fmt_result(o, r)
            tiers.setdefault(tier, []).append((O.fmt_args(o, args), expect, ",".join(note)))
        sections[o.id] = tiers
    return sections, notes


def tier_names(tiers):
    return sorted(tiers, key=lambda t: (TIER_ORDER.index(t) if t in TIER_ORDER else len(TIER_ORDER), t))


def legend(file):
    """Comment lines naming the core set of the file's type (for the reader)."""
    kind, _, ty = file.partition("-")
    if not ty:
        return []
    if ty in M.FLOATS:
        pairs = [("0x%0*x" % (M.fparams(ty)[0] // 4, v), n) for v, n in S.float_core_named(ty)]
        title = f"# core set of {ty} (the first operand set of the binary operations, a subset of the unary ones):"
    elif kind == "int":
        pairs = [(str(v), n) for v, n in S.int_core_named(ty)]
        title = f"# core set of {ty}:"
    else:
        return []
    lines, cur = [title], "#"
    for v, n in pairs:
        item = f" {v}={n};" if v != n else f" {v};"
        if len(cur) + len(item) > 110:
            lines.append(cur)
            cur = "#"
        cur += item
    lines.append(cur)
    return lines


def render_data(ops, sections):
    files = {}
    for o in ops:
        files.setdefault(o.file, []).append(o)
    out = {}
    for f, fops in files.items():
        lines = [PREAMBLE, *legend(f)]
        for o in fops:
            tiers = sections[o.id]
            for tier in tier_names(tiers):
                lines.append(f"@ {o.id} {tier}")
                for a, e, n in tiers[tier]:
                    lines.append(f"{a}\t{e}" + (f"\t{n}" if n else ""))
        out[f"{f}.tsv"] = ("\n".join(lines) + "\n").encode()
    return out


def render_ops_tsv(ops):
    def ty(t):
        return f"Option[{O.onsa_type(t[4:])}]" if t.startswith("opt:") else O.onsa_type(t)
    lines = [PREAMBLE, "# op\tfn\tfile\tpkg\targs\tret\tspec\ttokens\tonsa"]
    for o in ops:
        lines.append("\t".join([o.id, o.fn, o.file + ".tsv", o.pkg, " ".join(map(O.onsa_type, o.args)) or "()", ty(o.ret),
                                o.spec, " ".join(o.tokens) or "-", o.onsa if o.onsa else "(body)"]))
    return ("\n".join(lines) + "\n").encode()


# -------------------------------------------------------------- the fixture
def fn_text(o):
    params = ", ".join(f"{n}: {O.onsa_type(t)}" for n, t in zip("abc", o.args))
    if o.body:
        return o.body
    ret = o.ret
    if ret.startswith("opt:"):
        inner = O.onsa_type(ret[4:])
        zero = "0.0" if ret[4:] in M.FLOATS else "0"
        return (f"pub fn {o.fn}_some({params}) -> Bool {{\n  match {o.onsa} {{\n    Some(_) => true,\n    None => false,\n  }}\n}}\n\n"
                f"pub fn {o.fn}_val({params}) -> {inner} {{\n  match {o.onsa} {{\n    Some(v) => v,\n    None => {zero},\n  }}\n}}")
    return f"pub fn {o.fn}({params}) -> {O.onsa_type(ret)} {{ {o.onsa} }}"


def exported_fns(o):
    return [o.fn + "_some", o.fn + "_val"] if o.ret.startswith("opt:") else [o.fn]


def render_fixture(ops):
    out = {}
    for pkg in ["scalar"] + [n for n, _ in O.PENDING_PACKAGES]:
        pops = [o for o in ops if o.pkg == pkg]
        used = sorted({o.name for o in pops if o.group in ("int", "float") and o.name in O.STD_MATH})
        names = [f for o in pops for f in exported_fns(o)]
        head = [
            "// onsa.toml",
            "// [test]",
            '// spec = ["§3.3", "§3.4", "§6.6", "§11.4"]',
            "",
            f"// Package `{pkg}` of the scalar test vectors (tests/vectors/OPS.tsv, W2-01): one function per operation,",
            "// called with the boundary values of tests/vectors/*.tsv. Generated by tools/vectors/gen.py.",
        ]
        if pkg != "scalar":
            head += ["// These operations are not accepted yet (the rule in tools/vectors/ops.py, PENDING_PACKAGES): the package",
                     "// is a test case that waits in tests/pending.toml."]
        body = []
        if used:
            body += ["", f"use std.math.{{{', '.join(used)}}}"]
        for o in pops:
            body += ["", fn_text(o)]
        out[f"fixture/{pkg}/ops.onsa"] = ("\n".join(head + body) + "\n").encode()
        toml = [
            "[package]", f'name = "vector_{pkg}"', 'edition = "2026"', "",
            "[export]", 'prefix = "vec_"', "fns = [", *[f'  "ops.{n}",' for n in names], "]", "",
            "[targets.host]", 'kind = "source"', 'lang = "c"', 'platform = "host"', 'panic = "poison"', "provides = []",
        ]
        out[f"fixture/{pkg}/onsa.toml"] = ("\n".join(toml) + "\n").encode()
    return out


# -------------------------------------------------------------- the manifest
def data_hash(files):
    h = hashlib.sha256()
    for name in sorted(n for n in files if n.endswith(".tsv")):
        h.update(f"{name} {sha(files[name])}\n".encode())
    return h.hexdigest()


def render_manifest(files, sections, ops):
    counts = {}
    for o in ops:
        for tier, rows in sections[o.id].items():
            c = counts.setdefault(o.file + ".tsv", {})
            c[tier.split("-")[0] if tier.startswith("held") else tier] = c.get(tier.split("-")[0] if tier.startswith("held") else tier, 0) + len(rows)
    lines = [f"format {FORMAT_VERSION}", f"seed 0x{S.SEED:08x}", f"operations {len(ops)}", f"data_sha256 {data_hash(files)}"]
    for name in sorted(files):
        c = counts.get(name, {})
        extra = " ".join(f"{k}={c[k]}" for k in sorted(c))
        lines.append(f"file {name} sha256={sha(files[name])} rows={sum(c.values())}" + (f" {extra}" if extra else ""))
    return ("\n".join(lines) + "\n").encode()


def held_counts(sections):
    counts = {}
    for tiers in sections.values():
        for tier, rows in tiers.items():
            if tier.startswith("held-"):
                counts[tier] = counts.get(tier, 0) + len(rows)
    return counts


def generate():
    M.selftest()
    ops = O.registry()
    sections, notes = build_sections(ops)
    files = {}
    files.update(render_data(ops, sections))
    files["OPS.tsv"] = render_ops_tsv(ops)
    files.update(render_fixture(ops))
    files["MANIFEST"] = render_manifest(files, sections, ops)
    return ops, sections, notes, files


# ------------------------------------------------------------------- checks
def read_disk(root):
    out = {}
    if not root.is_dir():
        return out
    for p in sorted(root.rglob("*")):
        if p.is_file():
            rel = p.relative_to(root).as_posix()
            if rel not in HAND_WRITTEN:
                out[rel] = p.read_bytes()
    return out


def check(root=DATA, spec_path=SPEC, *, sections_override=None, quiet=False):
    t0 = time.time()
    problems = []
    try:
        ops, sections, notes, files = generate()
    except AssertionError:
        return ["the model fails its known-answer test (a rule of the model changed): " + " | ".join(traceback.format_exc().splitlines()[-3:])]
    disk = read_disk(root)
    for n in sorted(set(files) | set(disk)):
        if n not in disk:
            problems.append(f"{n}: not in {root} (run tools/vectors/gen.py --out tests/vectors)")
        elif n not in files:
            problems.append(f"{n}: in {root} but not generated")
        elif files[n] != disk[n]:
            problems.append(f"{n}: differs from the regenerated file ({sha(disk[n])[:12]} vs {sha(files[n])[:12]})")
    for n in sorted(HAND_WRITTEN):
        if not (root / n).is_file():
            problems.append(f"{n}: missing")
    problems += spec_tokens.check(ops, spec_path.read_text(encoding="utf-8"))
    problems += check_coverage(ops, sections, notes)
    problems += check_xcheck(root, data_hash(files))
    if not quiet:
        held = held_counts(sections)
        rows = sum(len(r) for t in sections.values() for r in t.values())
        print(f"vectors: {len(ops)} operations, {rows} rows, {len(files)} files, "
              f"held {sum(held.values())} ({', '.join(f'{k}={v}' for k, v in sorted(held.items())) or 'none'}), "
              f"{time.time() - t0:.1f}s")
    return problems


def check_coverage(ops, sections, notes):
    problems = []
    for o in ops:
        tiers = sections[o.id]
        if "edge" not in tiers or not tiers["edge"]:
            problems.append(f"{o.id}: no edge section")
    # 3.4: every panicking integer operation has a checked one (std.math functions have none)
    panics = {o.name for o in ops if o.group == "int" and not o.name.startswith("checked_") and o.name not in O.STD_MATH
              and any(e.startswith("panic:") for rows in sections[o.id].values() for _, e, _ in rows)}
    checked = {o.name[8:] for o in ops if o.group == "int" and o.name.startswith("checked_")}
    if panics != checked:
        problems.append(f"the panicking integer operations {sorted(panics)} are not the ones with a checked form {sorted(checked)}")
    seen = {}
    for o in ops:
        for tier, rows in sections[o.id].items():
            for a, e, n in rows:
                seen[(o.id, a)] = n
    by_id = {o.id: o for o in ops}
    for (op_id, args), note in notes.items():
        text = O.fmt_args(by_id[op_id], args)
        if (op_id, text) not in seen:
            problems.append(f"{op_id} {text}: the named case ({note}) is not in the data")
        elif note not in seen[(op_id, text)].split(","):
            problems.append(f"{op_id} {text}: the named case has the note {seen[(op_id, text)]!r}, not {note!r}")
    return problems


def check_xcheck(root, current):
    p = root / "XCHECK"
    if not p.is_file():
        return ["XCHECK: missing (run tools/vectors/xcheck.py after generating)"]
    recorded = None
    for line in p.read_text(encoding="utf-8").splitlines():
        if line.startswith("data_sha256 "):
            recorded = line.split()[1]
    if recorded != current:
        return [f"XCHECK: written for another data ({recorded}), not {current}: run tools/vectors/xcheck.py"]
    return []


def write(root):
    ops, sections, notes, files = generate()
    root.mkdir(parents=True, exist_ok=True)
    old = read_disk(root)
    for n in set(old) - set(files):
        (root / n).unlink()
    for n, b in files.items():
        p = root / n
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(b)
    rows = sum(len(r) for t in sections.values() for r in t.values())
    held = held_counts(sections)
    print(f"wrote {len(files)} files, {len(ops)} operations, {rows} rows, held {held}, data_sha256 {data_hash(files)}")


def explain(spec):
    path, _, line = spec.rpartition(":")
    ops = {o.id: o for o in O.registry()}
    cur = None
    for i, text in enumerate(Path(path).read_text().splitlines(), 1):
        if text.startswith("@ "):
            cur = text.split()[1]
        if i == int(line):
            if cur is None or text.startswith(("#", "@")):
                print(text)
                return
            o = ops[cur]
            cols = text.split("\t")
            print(f"{cur}: {o.onsa or '(body)'}   [{o.spec}]")
            for n, t, v in zip("abc", o.args, cols[0].split() if o.args else []):
                print(f"  {n} : {t} = {describe(t, v)}")
            print(f"  expected: {cols[1]}" + (f"   note: {cols[2]}" if len(cols) > 2 else ""))


def describe(t, text):
    if t in M.FLOATS:
        d = M.fdec(t, int(text, 16))
        if d[0] == "nan":
            return f"{text} NaN sign={d[1]} payload=0x{d[2]:x} ({'quiet' if d[2] >> (M.fparams(t)[1] - 2) else 'signaling'})"
        if d[0] == "inf":
            return f"{text} {'-' if d[1] else '+'}inf"
        return f"{text} {'-' if d[1] else '+'}{d[2]}" + (f" (about {float(d[2]):.9g})" if d[2] else "")
    return text


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--out", type=Path)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--explain")
    args = ap.parse_args(argv)
    if args.explain:
        explain(args.explain)
        return 0
    if args.out:
        write(args.out)
        return 0
    problems = check()
    for p in problems:
        print(f"FAIL {p}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
