/* ==== onsa_scaled.h ==== */
/* onsa_scaled.h — generated by onsa build for the flow `const_call.scaled`; do not edit. */
#ifndef ONSA_SCALED_H
#define ONSA_SCALED_H
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_SCALED_SIZE      2   /* bytes of the fast region (spec §12.4) */
#define ONSA_SCALED_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_SCALED_ALIGN     1
#define ONSA_SCALED_PARAM_COUNT 0

typedef struct onsa_scaled onsa_scaled;   /* the state (fast region); opaque */
typedef struct onsa_scaled_params { uint8_t onsa_empty; } onsa_scaled_params;

/* Memory is the caller's: `s` has ONSA_SCALED_SIZE bytes aligned to ONSA_SCALED_ALIGN, `bulk` has ONSA_SCALED_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_scaled_init(onsa_scaled* s, void* bulk, float sample_rate);
void onsa_scaled_reset(onsa_scaled* s);   /* clears `poisoned`; no effect on an uninitialized instance */
void onsa_scaled_params_default(onsa_scaled_params* p);
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_scaled_process(onsa_scaled* s, const onsa_scaled_params* p, const float* x, float* out, uint32_t frames);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_SCALED_H */
