/* onsa_const_call.c — generated by onsa build from package `const_call`; do not edit.
 *
 * Compile it with the flags of the target (spec §13.4): -std=c11 -ffp-contract=off -fno-fast-math -O2
 * In a GNU mode, GCC also needs -ffp-contract=off with the define ONSA_FP_CONTRACT_OFF.
 * onsa__runtime.h stops the compile when a flag the code needs is seen to be missing; the define
 * ONSA_ALLOW_INEXACT_FP removes those checks and gives up the bit-exact results. */
#define ONSA_PANIC_TRAP
#include "onsa__runtime.h"
#include "onsa_scaled.h"

/* ---- types ---- */
struct onsa_scaled { bool poisoned; bool initialized; };
typedef struct onsa_scaled const_call__scaled__State;
typedef onsa_scaled_params const_call__scaled__Params;
struct const_call__scaled__Config { uint8_t onsa_empty; };
typedef struct const_call__scaled__Config const_call__scaled__Config;
ONSA_DEFINE_SPAN(f32, float)
ONSA_DEFINE_SPAN_ADD_F32(f32)
ONSA_STATIC_ASSERT(sizeof(const_call__scaled__State) == ONSA_SCALED_SIZE, "ONSA_SCALED fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(const_call__scaled__State) == ONSA_SCALED_ALIGN, "ONSA_SCALED alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(const_call__scaled__State, poisoned) == 0, "ONSA_SCALED layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(const_call__scaled__State, initialized) == 1, "ONSA_SCALED layout prefix (spec §12.4)");

/* ---- constants ---- */
static const float const_call__HALF = 0.5f;

/* ---- functions ---- */
ONSA_INLINE void const_call__scaled__ctl(const_call__scaled__State* s, const const_call__scaled__Params* p);
ONSA_INLINE float const_call__scaled__tick(const_call__scaled__State* s, float x);
ONSA_INLINE void const_call__scaled__init(const_call__scaled__State* out, const const_call__scaled__Config* cfg, float sample_rate);
ONSA_INLINE void const_call__scaled__reset(const_call__scaled__State* s);
ONSA_INLINE void const_call__scaled__process(const_call__scaled__State* s, const const_call__scaled__Params* params, onsa_span_f32 x, onsa_span_f32 out);
ONSA_INLINE void const_call__scaled__params_default(const_call__scaled__Params* out);

ONSA_INLINE void const_call__scaled__ctl(const_call__scaled__State* s, const const_call__scaled__Params* p) {
  (void)s;
  (void)p;
}

ONSA_INLINE float const_call__scaled__tick(const_call__scaled__State* s, float x) {
  (void)s;
  float onsa__out = (float)(x * const_call__HALF);
  return onsa__out;
}

ONSA_INLINE void const_call__scaled__init(const_call__scaled__State* out, const const_call__scaled__Config* cfg, float sample_rate) {
  (void)cfg;
  (void)sample_rate;
  memset(&(*out), 0, sizeof (*out));
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void const_call__scaled__reset(const_call__scaled__State* s) {
  (void)s;
  s->poisoned = false;
}

ONSA_INLINE void const_call__scaled__process(const_call__scaled__State* s, const const_call__scaled__Params* params, onsa_span_f32 x, onsa_span_f32 out) {
  uint32_t len = x.len;
  if (out.len != len) {
    onsa_panic("span lengths differ", "const_call.onsa", 30);
  }
  const_call__scaled__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float x_7 = x.ptr[onsa_idx(i, x.len, "const_call.onsa", 30)];
    float v;
    float onsa_t2 = const_call__scaled__tick(&(*s), x_7);
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "const_call.onsa", 30)] = v;
  }
}

ONSA_INLINE void const_call__scaled__params_default(const_call__scaled__Params* out) {
  (*out) = ((const_call__scaled__Params){ .onsa_empty = 0 });
}

/* ---- export: const_call.scaled ---- */
int onsa_scaled_init(onsa_scaled* s, void* bulk, float sample_rate) {
  const_call__scaled__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  (void)bulk;
  const_call__scaled__init(s, &cfg, sample_rate);
  return 0;
}

void onsa_scaled_reset(onsa_scaled* s) { if (!s->initialized) return; const_call__scaled__reset(s); }

void onsa_scaled_params_default(onsa_scaled_params* p) { const_call__scaled__params_default(p); }

int onsa_scaled_process(onsa_scaled* s, const onsa_scaled_params* p, const float* x, float* out, uint32_t frames) {
  const_call__scaled__Params q;
  if (!s->initialized || s->poisoned) {
    if (frames != 0) {
      memset(out, 0, (size_t)frames * sizeof(float));
    }
    return 1;
  }
  if (frames != 0) {
    if (onsa_overlaps(x, (size_t)frames * sizeof(float), out, (size_t)frames * sizeof(float))) {
      memset(out, 0, (size_t)frames * sizeof(float));
      return 2;
    }
  }
  q = *p;
  const_call__scaled__process(s, &q, onsa_span_f32_of((float*)x, frames), onsa_span_f32_of(out, frames));
  return 0;
}

