/* onsa_echo.c — generated by onsa build from package `echo`; do not edit.
 *
 * Compile it with the flags of the target (spec §13.4): -std=c11 -ffp-contract=off -fno-fast-math -O2
 * In a GNU mode, GCC also needs -ffp-contract=off with the define ONSA_FP_CONTRACT_OFF.
 * onsa__runtime.h stops the compile when a flag the code needs is seen to be missing; the define
 * ONSA_ALLOW_INEXACT_FP removes those checks and gives up the bit-exact results. */
#define ONSA_PANIC_TRAP
#include "onsa__runtime.h"
#include "onsa_echo.h"

/* ---- types ---- */
typedef struct onsa_arr_f32_96001 { float a[96001]; } onsa_arr_f32_96001;
typedef struct echo__echo__State__Bulk { onsa_arr_f32_96001 vdelay_0_buf; } echo__echo__State__Bulk;
struct onsa_echo { void* bulk; float sample_rate; float feedback; float d; uint32_t vdelay_0_w; bool poisoned; bool initialized; };
typedef struct onsa_echo echo__echo__State;
typedef onsa_echo_params echo__echo__Params;
struct echo__echo__Config { uint8_t onsa_empty; };
typedef struct echo__echo__Config echo__echo__Config;
ONSA_DEFINE_SPAN(f32, float)
ONSA_DEFINE_SPAN_ADD_F32(f32)
ONSA_STATIC_ASSERT(sizeof(echo__echo__State) == ONSA_ECHO_SIZE, "ONSA_ECHO fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(echo__echo__State) == ONSA_ECHO_ALIGN, "ONSA_ECHO alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(echo__echo__State, poisoned) == 24, "ONSA_ECHO layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(echo__echo__State, initialized) == 25, "ONSA_ECHO layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(sizeof(echo__echo__State__Bulk) == 384004, "ONSA_ECHO bulk region size (spec §12.4)");

/* ---- functions ---- */
ONSA_INLINE void echo__echo__ctl(echo__echo__State* s, const echo__echo__Params* p);
ONSA_INLINE float echo__echo__tick(echo__echo__State* s, float x);
ONSA_INLINE void echo__echo__init(echo__echo__State* out, const echo__echo__Config* cfg, float sample_rate);
ONSA_INLINE void echo__echo__reset(echo__echo__State* s);
ONSA_INLINE void echo__echo__process(echo__echo__State* s, const echo__echo__Params* params, onsa_span_f32 x, onsa_span_f32 out);
ONSA_INLINE void echo__echo__params_default(echo__echo__Params* out);

ONSA_INLINE void echo__echo__ctl(echo__echo__State* s, const echo__echo__Params* p) {
  s->feedback = p->feedback;
  float d = (float)(p->time * s->sample_rate);
  s->d = d;
}

ONSA_INLINE float echo__echo__tick(echo__echo__State* s, float x) {
  float onsa_t4 = x;
  float onsa_t3 = s->feedback;
  float vdelay_0_d = s->d;
  float vdelay_0_dc;
  if (vdelay_0_d >= 1.0f) {
    if (vdelay_0_d <= 96000.0f) {
      vdelay_0_dc = vdelay_0_d;
    } else {
      vdelay_0_dc = 96000.0f;
    }
  } else {
    vdelay_0_dc = 1.0f;
  }
  uint32_t vdelay_0_k = onsa_trunc_u32_f32(vdelay_0_dc, "echo.onsa", 45);
  float vdelay_0_f = (float)(vdelay_0_dc - ((float)vdelay_0_k));
  uint32_t vdelay_0_wlk = onsa_sub_u32(onsa_add_u32(s->vdelay_0_w, UINT32_C(96001), "echo.onsa", 37), vdelay_0_k, "echo.onsa", 37);
  uint32_t onsa_t1 = onsa_rem_u32(vdelay_0_wlk, UINT32_C(96001), "echo.onsa", 45);
  float vdelay_0_a = (*(echo__echo__State__Bulk*)s->bulk).vdelay_0_buf.a[onsa_idx(onsa_t1, UINT32_C(96001), "echo.onsa", 37)];
  uint32_t onsa_t2 = onsa_rem_u32(onsa_sub_u32(vdelay_0_wlk, UINT32_C(1), "echo.onsa", 45), UINT32_C(96001), "echo.onsa", 45);
  float vdelay_0_b = (*(echo__echo__State__Bulk*)s->bulk).vdelay_0_buf.a[onsa_idx(onsa_t2, UINT32_C(96001), "echo.onsa", 37)];
  float vdelay_0 = (float)((float)((float)(1.0f - vdelay_0_f) * vdelay_0_a) + (float)(vdelay_0_f * vdelay_0_b));
  float y = (float)(onsa_t4 + (float)(onsa_t3 * vdelay_0));
  float onsa__out = y;
  (*(echo__echo__State__Bulk*)s->bulk).vdelay_0_buf.a[onsa_idx(s->vdelay_0_w, UINT32_C(96001), "echo.onsa", 37)] = y;
  s->vdelay_0_w = onsa_rem_u32(onsa_add_u32(s->vdelay_0_w, UINT32_C(1), "echo.onsa", 37), UINT32_C(96001), "echo.onsa", 37);
  return onsa__out;
}

ONSA_INLINE void echo__echo__init(echo__echo__State* out, const echo__echo__Config* cfg, float sample_rate) {
  (void)cfg;
  {
    void* onsa_b = (*out).bulk;
    memset(&(*out), 0, sizeof (*out));
    (*out).bulk = onsa_b;
    if (onsa_b) memset(onsa_b, 0, sizeof(echo__echo__State__Bulk));
  }
  out->sample_rate = sample_rate;
  float vdelay_0_init = 0.0f;
  {
    uint32_t onsa_i;
    for (onsa_i = 0; onsa_i < 96001; onsa_i++) (*(echo__echo__State__Bulk*)out->bulk).vdelay_0_buf.a[onsa_i] = vdelay_0_init;
  }
  out->vdelay_0_w = UINT32_C(0);
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void echo__echo__reset(echo__echo__State* s) {
  (void)s;
  {
    uint32_t onsa_i;
    for (onsa_i = 0; onsa_i < 96001; onsa_i++) (*(echo__echo__State__Bulk*)s->bulk).vdelay_0_buf.a[onsa_i] = 0.0f;
  }
  s->vdelay_0_w = UINT32_C(0);
  s->poisoned = false;
}

ONSA_INLINE void echo__echo__process(echo__echo__State* s, const echo__echo__Params* params, onsa_span_f32 x, onsa_span_f32 out) {
  uint32_t len = x.len;
  if (out.len != len) {
    onsa_panic("span lengths differ", "echo.onsa", 37);
  }
  echo__echo__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float x_11 = x.ptr[onsa_idx(i, x.len, "echo.onsa", 37)];
    float v;
    float onsa_t2 = echo__echo__tick(&(*s), x_11);
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "echo.onsa", 37)] = v;
  }
}

ONSA_INLINE void echo__echo__params_default(echo__echo__Params* out) {
  (*out) = ((echo__echo__Params){ .time = 0.3f, .feedback = 0.5f });
}

/* ---- export: echo.echo ---- */
int onsa_echo_init(onsa_echo* s, void* bulk, float sample_rate) {
  echo__echo__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  s->bulk = bulk;
  echo__echo__init(s, &cfg, sample_rate);
  return 0;
}

void onsa_echo_reset(onsa_echo* s) { if (!s->initialized) return; echo__echo__reset(s); }

void onsa_echo_params_default(onsa_echo_params* p) { echo__echo__params_default(p); }

int onsa_echo_process(onsa_echo* s, const onsa_echo_params* p, const float* x, float* out, uint32_t frames) {
  echo__echo__Params q;
  if (!s->initialized || s->poisoned) {
    if (frames != 0) {
      memset(out, 0, (size_t)frames * sizeof(float));
    }
    return 1;
  }
  if (frames != 0) {
    if (onsa_overlaps(x, (size_t)frames * sizeof(float), out, (size_t)frames * sizeof(float))) {
      memset(out, 0, (size_t)frames * sizeof(float));
      return 2;
    }
  }
  q = *p;
  q.time = onsa_clamp_f32(q.time, 0.01f, 1.0f);
  q.feedback = onsa_clamp_f32(q.feedback, 0.0f, 0.95f);
  echo__echo__process(s, &q, onsa_span_f32_of((float*)x, frames), onsa_span_f32_of(out, frames));
  return 0;
}

const onsa_param_info onsa_echo_param_info[2] = {
  { "time", "time", 0.01f, 1.0f, 0.3f, NAN, "s", "linear", "" },
  { "feedback", "feedback", 0.0f, 0.95f, 0.5f, NAN, "", "linear", "" },
};

