/* ==== onsa_echo.h ==== */
/* onsa_echo.h — generated by onsa build for the flow `echo.echo`; do not edit. */
#ifndef ONSA_ECHO_H
#define ONSA_ECHO_H
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_ECHO_SIZE      32   /* bytes of the fast region (spec §12.4) */
#define ONSA_ECHO_BULK_SIZE 384004   /* bytes of the bulk region */
#define ONSA_ECHO_ALIGN     8
#define ONSA_ECHO_PARAM_COUNT 2

typedef struct onsa_echo onsa_echo;   /* the state (fast region); opaque */
typedef struct onsa_echo_params { float time; float feedback; } onsa_echo_params;

/* Memory is the caller's: `s` has ONSA_ECHO_SIZE bytes aligned to ONSA_ECHO_ALIGN, `bulk` has ONSA_ECHO_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_echo_init(onsa_echo* s, void* bulk, float sample_rate);
void onsa_echo_reset(onsa_echo* s);   /* clears `poisoned`; no effect on an uninitialized instance */
void onsa_echo_params_default(onsa_echo_params* p);
/* 0: ok, 1: poisoned or uninitialized, 2: overlapping buffers that are not an in-place pair (an in-place pair
 * is an input and an output of the same element type at the same pointer). On 1 and 2 all outputs are zero. */
int  onsa_echo_process(onsa_echo* s, const onsa_echo_params* p, const float* x, float* out, uint32_t frames);
extern const onsa_param_info onsa_echo_param_info[2];

/* Convenience on targets with a heap. */
onsa_echo* onsa_echo_new(float sample_rate);   /* NULL when out of memory or `init` panicked */
void onsa_echo_free(onsa_echo* s);

/* panic = "poison" (spec §9.2): a panic inside `process` zeroes the outputs, poisons the instance
 * (`process` returns 1 until `reset`); a panic inside an exported function returns a zero value and
 * onsa_take_panic() reports it once. */
int onsa_take_panic(void);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_ECHO_H */
