/* ==== onsa_resonator.h ==== */
/* onsa_resonator.h — generated by onsa build for the flow `resonator.resonator`; do not edit. */
#ifndef ONSA_RESONATOR_H
#define ONSA_RESONATOR_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_RESONATOR_SIZE      28   /* bytes of the fast region (spec §12.4) */
#define ONSA_RESONATOR_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_RESONATOR_ALIGN     4
#define ONSA_RESONATOR_PARAM_COUNT 2

typedef struct onsa_resonator onsa_resonator;   /* the state (fast region); opaque */
typedef struct onsa_resonator_params { float fc; float bw; } onsa_resonator_params;

/* Memory is the caller's: `s` has ONSA_RESONATOR_SIZE bytes aligned to ONSA_RESONATOR_ALIGN, `bulk` has ONSA_RESONATOR_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_resonator_init(onsa_resonator* s, void* bulk, float sample_rate);
void onsa_resonator_reset(onsa_resonator* s);   /* clears `poisoned`; no effect on an uninitialized instance */
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_resonator_process(onsa_resonator* s, const onsa_resonator_params* p, const float* x, float* out, uint32_t frames);
extern const onsa_param_info onsa_resonator_param_info[2];

#ifdef __cplusplus
}
#endif
#endif /* ONSA_RESONATOR_H */
