/* onsa_resonator.c — generated by onsa build from package `resonator`; do not edit. */
#define ONSA_PANIC_TRAP
#include "onsa.h"
#include "onsa_resonator.h"

/* ---- types ---- */
struct onsa_resonator { float sample_rate; float r; float b1; float b2; float y1; float y2; bool poisoned; bool initialized; };
typedef struct onsa_resonator resonator__resonator__State;
typedef onsa_resonator_params resonator__resonator__Params;
struct resonator__resonator__Config { uint8_t onsa_empty; };
typedef struct resonator__resonator__Config resonator__resonator__Config;
ONSA_DEFINE_SPAN(f32, float)
ONSA_DEFINE_SPAN_ADD_F32(f32)
ONSA_STATIC_ASSERT(sizeof(resonator__resonator__State) == ONSA_RESONATOR_SIZE, "ONSA_RESONATOR fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(resonator__resonator__State) == ONSA_RESONATOR_ALIGN, "ONSA_RESONATOR alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(resonator__resonator__State, poisoned) == 24, "ONSA_RESONATOR layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(resonator__resonator__State, initialized) == 25, "ONSA_RESONATOR layout prefix (spec §12.4)");

/* ---- functions ---- */
ONSA_INLINE void resonator__resonator__ctl(resonator__resonator__State* s, const resonator__resonator__Params* p);
ONSA_INLINE float resonator__resonator__tick(resonator__resonator__State* s, float x);
ONSA_INLINE void resonator__resonator__init(resonator__resonator__State* out, const resonator__resonator__Config* cfg, float sample_rate);
ONSA_INLINE void resonator__resonator__reset(resonator__resonator__State* s);
ONSA_INLINE void resonator__resonator__process(resonator__resonator__State* s, const resonator__resonator__Params* params, onsa_span_f32 x, onsa_span_f32 out);

ONSA_INLINE void resonator__resonator__ctl(resonator__resonator__State* s, const resonator__resonator__Params* p) {
  float r = expf((float)((float)(-(float)(3.1415927f * p->bw)) / s->sample_rate));
  s->r = r;
  float w = (float)((float)((float)(2.0f * 3.1415927f) * p->fc) / s->sample_rate);
  float b1 = (float)((float)(2.0f * r) * cosf(w));
  s->b1 = b1;
  float b2 = (float)(r * r);
  s->b2 = b2;
}

ONSA_INLINE float resonator__resonator__tick(resonator__resonator__State* s, float x) {
  float y1;
  float y1_11 = s->y1;
  y1 = y1_11;
  float y2;
  float y2_12 = s->y2;
  y2 = y2_12;
  float y = (float)((float)((float)((float)(1.0f - s->r) * x) + (float)(s->b1 * y1)) - (float)(s->b2 * y2));
  float onsa__out = y;
  s->y1 = y;
  s->y2 = y1;
  return onsa__out;
}

ONSA_INLINE void resonator__resonator__init(resonator__resonator__State* out, const resonator__resonator__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  out->sample_rate = sample_rate;
  float y1_init = 0.0f;
  out->y1 = y1_init;
  float y2_init = 0.0f;
  out->y2 = y2_init;
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void resonator__resonator__reset(resonator__resonator__State* s) {
  s->y1 = 0.0f;
  s->y2 = 0.0f;
  s->poisoned = false;
}

ONSA_INLINE void resonator__resonator__process(resonator__resonator__State* s, const resonator__resonator__Params* params, onsa_span_f32 x, onsa_span_f32 out) {
  uint32_t len = x.len;
  if ((out.len != len)) {
    onsa_panic("span lengths differ", "resonator.onsa", 4);
  }
  resonator__resonator__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float x_16 = x.ptr[onsa_idx(i, x.len, "resonator.onsa", 4)];
    float v;
    float onsa_t2 = resonator__resonator__tick(&(*s), x_16);
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "resonator.onsa", 4)] = v;
  }
}

/* ---- export: resonator.resonator ---- */
int onsa_resonator_init(onsa_resonator* s, void* bulk, float sample_rate) {
  resonator__resonator__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  (void)bulk;
  resonator__resonator__init(s, &cfg, sample_rate);
  return 0;
}

void onsa_resonator_reset(onsa_resonator* s) { if (!s->initialized) return; resonator__resonator__reset(s); }

int onsa_resonator_process(onsa_resonator* s, const onsa_resonator_params* p, const float* x, float* out, uint32_t frames) {
  resonator__resonator__Params q;
  if (!s->initialized || s->poisoned) return 1;
  if (onsa_overlaps(x, (size_t)frames * sizeof(float), out, (size_t)frames * sizeof(float))) return 2;
  q = *p;
  resonator__resonator__process(s, &q, onsa_span_f32_of((float*)x, frames), onsa_span_f32_of(out, frames));
  return 0;
}

const onsa_param_info onsa_resonator_param_info[2] = {
  { "fc", "fc", NAN, NAN, NAN, NAN, "", "linear", "" },
  { "bw", "bw", NAN, NAN, NAN, NAN, "", "linear", "" },
};

