/* onsa_unison.c — generated by onsa build from package `unison`; do not edit. */
#define ONSA_PANIC_TRAP
#include "onsa.h"
#include "onsa_saw.h"
#include "onsa_unison.h"

/* ---- types ---- */
struct onsa_saw { float sample_rate; float f0; float prev_0; bool poisoned; bool initialized; };
typedef struct onsa_saw unison__saw__State;
typedef onsa_saw_params unison__saw__Params;
struct unison__saw__Config { uint8_t onsa_empty; };
typedef struct unison__saw__Config unison__saw__Config;
ONSA_DEFINE_SPAN(f32, float)
ONSA_DEFINE_SPAN_ADD_F32(f32)
struct unison__unison__saws__State { unison__saw__State saw_0; };
typedef struct unison__unison__saws__State unison__unison__saws__State;
typedef struct onsa_arr_unison__unison__saws__State_4 { unison__unison__saws__State a[4]; } onsa_arr_unison__unison__saws__State_4;
struct onsa_unison { onsa_arr_unison__unison__saws__State_4 saws; bool poisoned; bool initialized; };
typedef struct onsa_unison unison__unison__State;
typedef onsa_unison_params unison__unison__Params;
typedef struct onsa_arr_f32_4 { float a[4]; } onsa_arr_f32_4;
struct unison__unison__Config { uint8_t onsa_empty; };
typedef struct unison__unison__Config unison__unison__Config;
ONSA_STATIC_ASSERT(sizeof(unison__saw__State) == ONSA_SAW_SIZE, "ONSA_SAW fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(unison__saw__State) == ONSA_SAW_ALIGN, "ONSA_SAW alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(unison__saw__State, poisoned) == 12, "ONSA_SAW layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(unison__saw__State, initialized) == 13, "ONSA_SAW layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(sizeof(unison__unison__State) == ONSA_UNISON_SIZE, "ONSA_UNISON fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(unison__unison__State) == ONSA_UNISON_ALIGN, "ONSA_UNISON alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(unison__unison__State, poisoned) == 64, "ONSA_UNISON layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(unison__unison__State, initialized) == 65, "ONSA_UNISON layout prefix (spec §12.4)");

/* ---- constants ---- */
static const uint32_t unison__UNISON = UINT32_C(4);

/* ---- functions ---- */
ONSA_INLINE void unison__saw__ctl(unison__saw__State* s, const unison__saw__Params* p);
ONSA_INLINE float unison__saw__tick(unison__saw__State* s);
ONSA_INLINE void unison__saw__init(unison__saw__State* out, const unison__saw__Config* cfg, float sample_rate);
ONSA_INLINE void unison__saw__reset(unison__saw__State* s);
ONSA_INLINE void unison__saw__process(unison__saw__State* s, const unison__saw__Params* params, onsa_span_f32 out);
ONSA_INLINE float unison__wrap01(float x);
ONSA_INLINE void unison__unison__ctl(unison__unison__State* s, const unison__unison__Params* p);
ONSA_INLINE float unison__unison__tick(unison__unison__State* s);
ONSA_INLINE void unison__unison__init(unison__unison__State* out, const unison__unison__Config* cfg, float sample_rate);
ONSA_INLINE void unison__unison__reset(unison__unison__State* s);
ONSA_INLINE void unison__unison__process(unison__unison__State* s, const unison__unison__Params* params, onsa_span_f32 out);
ONSA_INLINE float unison__spread(uint32_t i, uint32_t n);
ONSA_INLINE float std__dsp__sum__4(const onsa_arr_f32_4* xs);

ONSA_INLINE void unison__saw__ctl(unison__saw__State* s, const unison__saw__Params* p) {
  s->f0 = p->f0;
}

ONSA_INLINE float unison__saw__tick(unison__saw__State* s) {
  float phase;
  float prev_0 = s->prev_0;
  float onsa_t1 = unison__wrap01((float)(prev_0 + (float)(s->f0 / s->sample_rate)));
  phase = onsa_t1;
  float onsa__out = (float)((float)(2.0f * phase) - 1.0f);
  s->prev_0 = phase;
  return onsa__out;
}

ONSA_INLINE void unison__saw__init(unison__saw__State* out, const unison__saw__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  out->sample_rate = sample_rate;
  float prev_0_init = 0.0f;
  out->prev_0 = prev_0_init;
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void unison__saw__reset(unison__saw__State* s) {
  s->prev_0 = 0.0f;
  s->poisoned = false;
}

ONSA_INLINE void unison__saw__process(unison__saw__State* s, const unison__saw__Params* params, onsa_span_f32 out) {
  uint32_t len = out.len;
  unison__saw__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float v;
    float onsa_t2 = unison__saw__tick(&(*s));
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "unison.onsa", 20)] = v;
  }
}

ONSA_INLINE float unison__wrap01(float x) {
  return (float)(x - floorf(x));
}

ONSA_INLINE void unison__unison__ctl(unison__unison__State* s, const unison__unison__Params* p) {
  for (uint32_t i = UINT32_C(0); i < UINT32_C(4); i++) {
    float onsa_t3 = p->f0;
    float onsa_t2 = p->detune;
    float onsa_t1 = unison__spread(i, unison__UNISON);
    unison__saw__Params onsa_t4 = ((unison__saw__Params){ .f0 = (float)(onsa_t3 * (float)(1.0f + (float)(onsa_t2 * onsa_t1))) });
    unison__saw__ctl(&s->saws.a[onsa_idx(i, UINT32_C(4), "unison.onsa", 6)].saw_0, &onsa_t4);
  }
}

ONSA_INLINE float unison__unison__tick(unison__unison__State* s) {
  onsa_arr_f32_4 saws;
  onsa_arr_f32_4 saws_5;
  memset(&saws_5, 0, sizeof saws_5);
  for (uint32_t i = UINT32_C(0); i < UINT32_C(4); i++) {
    float saw_0;
    float onsa_t1 = unison__saw__tick(&s->saws.a[onsa_idx(i, UINT32_C(4), "unison.onsa", 6)].saw_0);
    saw_0 = onsa_t1;
    saws_5.a[onsa_idx(i, UINT32_C(4), "unison.onsa", 6)] = saw_0;
  }
  saws = saws_5;
  float onsa_t2 = std__dsp__sum__4(&saws);
  float onsa__out = (float)(onsa_t2 * 0.25f);
  return onsa__out;
}

ONSA_INLINE void unison__unison__init(unison__unison__State* out, const unison__unison__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  for (uint32_t i = UINT32_C(0); i < UINT32_C(4); i++) {
    unison__saw__Config onsa_t1 = ((unison__saw__Config){ .onsa_empty = 0 });
    unison__saw__init(&out->saws.a[onsa_idx(i, UINT32_C(4), "unison.onsa", 6)].saw_0, &onsa_t1, sample_rate);
  }
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void unison__unison__reset(unison__unison__State* s) {
  for (uint32_t i = UINT32_C(0); i < UINT32_C(4); i++) {
    unison__saw__reset(&s->saws.a[onsa_idx(i, UINT32_C(4), "unison.onsa", 6)].saw_0);
  }
  s->poisoned = false;
}

ONSA_INLINE void unison__unison__process(unison__unison__State* s, const unison__unison__Params* params, onsa_span_f32 out) {
  uint32_t len = out.len;
  unison__unison__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float v;
    float onsa_t2 = unison__unison__tick(&(*s));
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "unison.onsa", 5)] = v;
  }
}

ONSA_INLINE float unison__spread(uint32_t i, uint32_t n) {
  return (float)((float)(((float)i) / ((float)onsa_sub_u32(n, UINT32_C(1), "unison.onsa", 14))) - 0.5f);
}

ONSA_INLINE float std__dsp__sum__4(const onsa_arr_f32_4* xs) {
  float acc = 0.0f;
  for (uint32_t i = UINT32_C(0); i < UINT32_C(4); i++) {
    acc = (float)(acc + (*xs).a[onsa_idx(i, UINT32_C(4), "dsp.onsa", 10)]);
  }
  return acc;
}

/* ---- export: unison.saw ---- */
int onsa_saw_init(onsa_saw* s, void* bulk, float sample_rate) {
  unison__saw__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  (void)bulk;
  unison__saw__init(s, &cfg, sample_rate);
  return 0;
}

void onsa_saw_reset(onsa_saw* s) { if (!s->initialized) return; unison__saw__reset(s); }

int onsa_saw_process(onsa_saw* s, const onsa_saw_params* p, float* out, uint32_t frames) {
  unison__saw__Params q;
  if (!s->initialized || s->poisoned) return 1;
  q = *p;
  unison__saw__process(s, &q, onsa_span_f32_of(out, frames));
  return 0;
}

const onsa_param_info onsa_saw_param_info[1] = {
  { "f0", "f0", NAN, NAN, NAN, NAN, "", "linear", "" },
};

/* ---- export: unison.unison ---- */
int onsa_unison_init(onsa_unison* s, void* bulk, float sample_rate) {
  unison__unison__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  (void)bulk;
  unison__unison__init(s, &cfg, sample_rate);
  return 0;
}

void onsa_unison_reset(onsa_unison* s) { if (!s->initialized) return; unison__unison__reset(s); }

int onsa_unison_process(onsa_unison* s, const onsa_unison_params* p, float* out, uint32_t frames) {
  unison__unison__Params q;
  if (!s->initialized || s->poisoned) return 1;
  q = *p;
  unison__unison__process(s, &q, onsa_span_f32_of(out, frames));
  return 0;
}

const onsa_param_info onsa_unison_param_info[2] = {
  { "f0", "f0", NAN, NAN, NAN, NAN, "", "linear", "" },
  { "detune", "detune", NAN, NAN, NAN, NAN, "", "linear", "" },
};

