/* ==== onsa_saw.h ==== */
/* onsa_saw.h — generated by onsa build for the flow `unison.saw`; do not edit. */
#ifndef ONSA_SAW_H
#define ONSA_SAW_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_SAW_SIZE      16   /* bytes of the fast region (spec §12.4) */
#define ONSA_SAW_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_SAW_ALIGN     4
#define ONSA_SAW_PARAM_COUNT 1

typedef struct onsa_saw onsa_saw;   /* the state (fast region); opaque */
typedef struct onsa_saw_params { float f0; } onsa_saw_params;

/* Memory is the caller's: `s` has ONSA_SAW_SIZE bytes aligned to ONSA_SAW_ALIGN, `bulk` has ONSA_SAW_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_saw_init(onsa_saw* s, void* bulk, float sample_rate);
void onsa_saw_reset(onsa_saw* s);   /* clears `poisoned`; no effect on an uninitialized instance */
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_saw_process(onsa_saw* s, const onsa_saw_params* p, float* out, uint32_t frames);
extern const onsa_param_info onsa_saw_param_info[1];

#ifdef __cplusplus
}
#endif
#endif /* ONSA_SAW_H */
/* ==== onsa_unison.h ==== */
/* onsa_unison.h — generated by onsa build for the flow `unison.unison`; do not edit. */
#ifndef ONSA_UNISON_H
#define ONSA_UNISON_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_UNISON_SIZE      68   /* bytes of the fast region (spec §12.4) */
#define ONSA_UNISON_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_UNISON_ALIGN     4
#define ONSA_UNISON_PARAM_COUNT 2

typedef struct onsa_unison onsa_unison;   /* the state (fast region); opaque */
typedef struct onsa_unison_params { float f0; float detune; } onsa_unison_params;

/* Memory is the caller's: `s` has ONSA_UNISON_SIZE bytes aligned to ONSA_UNISON_ALIGN, `bulk` has ONSA_UNISON_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_unison_init(onsa_unison* s, void* bulk, float sample_rate);
void onsa_unison_reset(onsa_unison* s);   /* clears `poisoned`; no effect on an uninitialized instance */
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_unison_process(onsa_unison* s, const onsa_unison_params* p, float* out, uint32_t frames);
extern const onsa_param_info onsa_unison_param_info[2];

#ifdef __cplusplus
}
#endif
#endif /* ONSA_UNISON_H */
