/* onsa_voice.c — generated by onsa build from package `voice`; do not edit.
 *
 * Compile it with the flags of the target (spec §13.4): -std=c11 -ffp-contract=off -fno-fast-math -O2
 * In a GNU mode, GCC also needs -ffp-contract=off with the define ONSA_FP_CONTRACT_OFF.
 * onsa__runtime.h stops the compile when a flag the code needs is seen to be missing; the define
 * ONSA_ALLOW_INEXACT_FP removes those checks and gives up the bit-exact results. */
#define ONSA_PANIC_POISON
#include "onsa__runtime.h"
#include "onsa_voice.h"
#include "onsa_echo.h"

/* ---- types ---- */
struct voice__resonator__State { float sample_rate; float r; float b1; float b2; float y1; float y2; bool poisoned; bool initialized; };
typedef struct voice__resonator__State voice__resonator__State;
struct voice__resonator__Params { float fc; float bw; };
typedef struct voice__resonator__Params voice__resonator__Params;
struct voice__resonator__Config { uint8_t onsa_empty; };
typedef struct voice__resonator__Config voice__resonator__Config;
struct voice__saw__State { float sample_rate; float f0; float prev_0; bool poisoned; bool initialized; };
typedef struct voice__saw__State voice__saw__State;
struct voice__saw__Params { float f0; };
typedef struct voice__saw__Params voice__saw__Params;
struct voice__saw__Config { uint8_t onsa_empty; };
typedef struct voice__saw__Config voice__saw__Config;
struct voice__smooth__State { float x; float a; float prev_0; bool poisoned; bool initialized; };
typedef struct voice__smooth__State voice__smooth__State;
struct voice__smooth__Params { float x; };
typedef struct voice__smooth__Params voice__smooth__Params;
struct voice__smooth__Config { float time; };
typedef struct voice__smooth__Config voice__smooth__Config;
struct onsa_voice { voice__saw__State src; voice__resonator__State f1; voice__resonator__State f2; voice__smooth__State smooth_0; bool poisoned; bool initialized; };
typedef struct onsa_voice voice__voice__State;
typedef onsa_voice_params voice__voice__Params;
struct voice__voice__Config { uint8_t onsa_empty; };
typedef struct voice__voice__Config voice__voice__Config;
ONSA_DEFINE_SPAN(f32, float)
ONSA_DEFINE_SPAN_ADD_F32(f32)
typedef struct onsa_arr_f32_96001 { float a[96001]; } onsa_arr_f32_96001;
struct onsa_echo { float sample_rate; float feedback; float d; onsa_arr_f32_96001 vdelay_0_buf; uint32_t vdelay_0_w; bool poisoned; bool initialized; };
typedef struct onsa_echo voice__echo__State;
typedef onsa_echo_params voice__echo__Params;
struct voice__echo__Config { uint8_t onsa_empty; };
typedef struct voice__echo__Config voice__echo__Config;
ONSA_STATIC_ASSERT(sizeof(voice__voice__State) == ONSA_VOICE_SIZE, "ONSA_VOICE fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(voice__voice__State) == ONSA_VOICE_ALIGN, "ONSA_VOICE alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(voice__voice__State, poisoned) == 88, "ONSA_VOICE layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(voice__voice__State, initialized) == 89, "ONSA_VOICE layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(sizeof(voice__echo__State) == ONSA_ECHO_SIZE, "ONSA_ECHO fast region size (spec §12.4)");
ONSA_STATIC_ASSERT(ONSA_ALIGNOF(voice__echo__State) == ONSA_ECHO_ALIGN, "ONSA_ECHO alignment (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(voice__echo__State, poisoned) == 384020, "ONSA_ECHO layout prefix (spec §12.4)");
ONSA_STATIC_ASSERT(offsetof(voice__echo__State, initialized) == 384021, "ONSA_ECHO layout prefix (spec §12.4)");

/* ---- functions ---- */
ONSA_INLINE void voice__resonator__ctl(voice__resonator__State* s, const voice__resonator__Params* p);
ONSA_INLINE float voice__resonator__tick(voice__resonator__State* s, float x);
ONSA_INLINE void voice__resonator__init(voice__resonator__State* out, const voice__resonator__Config* cfg, float sample_rate);
ONSA_INLINE void voice__resonator__reset(voice__resonator__State* s);
ONSA_INLINE void voice__saw__ctl(voice__saw__State* s, const voice__saw__Params* p);
ONSA_INLINE float voice__saw__tick(voice__saw__State* s);
ONSA_INLINE void voice__saw__init(voice__saw__State* out, const voice__saw__Config* cfg, float sample_rate);
ONSA_INLINE void voice__saw__reset(voice__saw__State* s);
ONSA_INLINE float voice__wrap01(float x);
ONSA_INLINE void voice__smooth__ctl(voice__smooth__State* s, const voice__smooth__Params* p);
ONSA_INLINE float voice__smooth__tick(voice__smooth__State* s);
ONSA_INLINE void voice__smooth__init(voice__smooth__State* out, const voice__smooth__Config* cfg, float sample_rate);
ONSA_INLINE void voice__smooth__reset(voice__smooth__State* s);
ONSA_INLINE void voice__voice__ctl(voice__voice__State* s, const voice__voice__Params* p);
ONSA_INLINE float voice__voice__tick(voice__voice__State* s);
ONSA_INLINE void voice__voice__init(voice__voice__State* out, const voice__voice__Config* cfg, float sample_rate);
ONSA_INLINE void voice__voice__reset(voice__voice__State* s);
ONSA_INLINE void voice__voice__process(voice__voice__State* s, const voice__voice__Params* params, onsa_span_f32 out);
ONSA_INLINE void voice__voice__params_default(voice__voice__Params* out);
ONSA_INLINE void voice__echo__ctl(voice__echo__State* s, const voice__echo__Params* p);
ONSA_INLINE float voice__echo__tick(voice__echo__State* s, float x);
ONSA_INLINE void voice__echo__init(voice__echo__State* out, const voice__echo__Config* cfg, float sample_rate);
ONSA_INLINE void voice__echo__reset(voice__echo__State* s);
ONSA_INLINE void voice__echo__process(voice__echo__State* s, const voice__echo__Params* params, onsa_span_f32 x, onsa_span_f32 out);
ONSA_INLINE void voice__echo__params_default(voice__echo__Params* out);

ONSA_INLINE void voice__resonator__ctl(voice__resonator__State* s, const voice__resonator__Params* p) {
  float r = expf((float)((float)(-(float)(3.1415927f * p->bw)) / s->sample_rate));
  s->r = r;
  float w = (float)((float)((float)(2.0f * 3.1415927f) * p->fc) / s->sample_rate);
  float b1 = (float)((float)(2.0f * r) * cosf(w));
  s->b1 = b1;
  float b2 = (float)(r * r);
  s->b2 = b2;
}

ONSA_INLINE float voice__resonator__tick(voice__resonator__State* s, float x) {
  float y1;
  float y1_11 = s->y1;
  y1 = y1_11;
  float y2;
  float y2_12 = s->y2;
  y2 = y2_12;
  float y = (float)((float)((float)((float)(1.0f - s->r) * x) + (float)(s->b1 * y1)) - (float)(s->b2 * y2));
  float onsa__out = y;
  s->y1 = y;
  s->y2 = y1;
  return onsa__out;
}

ONSA_INLINE void voice__resonator__init(voice__resonator__State* out, const voice__resonator__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  out->sample_rate = sample_rate;
  float y1_init = 0.0f;
  out->y1 = y1_init;
  float y2_init = 0.0f;
  out->y2 = y2_init;
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void voice__resonator__reset(voice__resonator__State* s) {
  (void)s;
  s->y1 = 0.0f;
  s->y2 = 0.0f;
  s->poisoned = false;
}

ONSA_INLINE void voice__saw__ctl(voice__saw__State* s, const voice__saw__Params* p) {
  (void)s;
  s->f0 = p->f0;
}

ONSA_INLINE float voice__saw__tick(voice__saw__State* s) {
  float phase;
  float prev_0 = s->prev_0;
  float onsa_t1 = voice__wrap01((float)(prev_0 + (float)(s->f0 / s->sample_rate)));
  phase = onsa_t1;
  float onsa__out = (float)((float)(2.0f * phase) - 1.0f);
  s->prev_0 = phase;
  return onsa__out;
}

ONSA_INLINE void voice__saw__init(voice__saw__State* out, const voice__saw__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  out->sample_rate = sample_rate;
  float prev_0_init = 0.0f;
  out->prev_0 = prev_0_init;
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void voice__saw__reset(voice__saw__State* s) {
  (void)s;
  s->prev_0 = 0.0f;
  s->poisoned = false;
}

ONSA_INLINE float voice__wrap01(float x) {
  return (float)(x - floorf(x));
}

ONSA_INLINE void voice__smooth__ctl(voice__smooth__State* s, const voice__smooth__Params* p) {
  (void)s;
  s->x = p->x;
}

ONSA_INLINE float voice__smooth__tick(voice__smooth__State* s) {
  float onsa_t2 = s->x;
  float onsa_t1 = s->a;
  float prev_0 = s->prev_0;
  float y = (float)(onsa_t2 + (float)(onsa_t1 * (float)(prev_0 - s->x)));
  float onsa__out = y;
  s->prev_0 = y;
  return onsa__out;
}

ONSA_INLINE void voice__smooth__init(voice__smooth__State* out, const voice__smooth__Config* cfg, float sample_rate) {
  memset(&(*out), 0, sizeof (*out));
  float a = expf((float)(-1.0f / (float)(cfg->time * sample_rate)));
  out->a = a;
  float prev_0_init = 0.0f;
  out->prev_0 = prev_0_init;
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void voice__smooth__reset(voice__smooth__State* s) {
  (void)s;
  s->prev_0 = 0.0f;
  s->poisoned = false;
}

ONSA_INLINE void voice__voice__ctl(voice__voice__State* s, const voice__voice__Params* p) {
  voice__saw__Params onsa_t1 = ((voice__saw__Params){ .f0 = p->f0 });
  voice__saw__ctl(&s->src, &onsa_t1);
  voice__resonator__Params onsa_t2 = ((voice__resonator__Params){ .fc = p->vowel_f1, .bw = 80.0f });
  voice__resonator__ctl(&s->f1, &onsa_t2);
  voice__resonator__Params onsa_t3 = ((voice__resonator__Params){ .fc = p->vowel_f2, .bw = 120.0f });
  voice__resonator__ctl(&s->f2, &onsa_t3);
  voice__smooth__Params onsa_t4 = ((voice__smooth__Params){ .x = p->gain });
  voice__smooth__ctl(&s->smooth_0, &onsa_t4);
}

ONSA_INLINE float voice__voice__tick(voice__voice__State* s) {
  float src;
  float src_8;
  float onsa_t1 = voice__saw__tick(&s->src);
  src_8 = onsa_t1;
  src = src_8;
  float f1;
  float f1_9;
  float onsa_t2 = voice__resonator__tick(&s->f1, src);
  f1_9 = onsa_t2;
  f1 = f1_9;
  float f2;
  float f2_10;
  float onsa_t3 = voice__resonator__tick(&s->f2, src);
  f2_10 = onsa_t3;
  f2 = f2_10;
  float onsa_t5 = (float)(f1 + f2);
  float smooth_0;
  float onsa_t4 = voice__smooth__tick(&s->smooth_0);
  smooth_0 = onsa_t4;
  float onsa__out = (float)(onsa_t5 * smooth_0);
  return onsa__out;
}

ONSA_INLINE void voice__voice__init(voice__voice__State* out, const voice__voice__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  voice__saw__Config onsa_t1 = ((voice__saw__Config){ .onsa_empty = 0 });
  voice__saw__init(&out->src, &onsa_t1, sample_rate);
  voice__resonator__Config onsa_t2 = ((voice__resonator__Config){ .onsa_empty = 0 });
  voice__resonator__init(&out->f1, &onsa_t2, sample_rate);
  voice__resonator__Config onsa_t3 = ((voice__resonator__Config){ .onsa_empty = 0 });
  voice__resonator__init(&out->f2, &onsa_t3, sample_rate);
  voice__smooth__Config onsa_t4 = ((voice__smooth__Config){ .time = 0.01f });
  voice__smooth__init(&out->smooth_0, &onsa_t4, sample_rate);
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void voice__voice__reset(voice__voice__State* s) {
  voice__saw__reset(&s->src);
  voice__resonator__reset(&s->f1);
  voice__resonator__reset(&s->f2);
  voice__smooth__reset(&s->smooth_0);
  s->poisoned = false;
}

ONSA_INLINE void voice__voice__process(voice__voice__State* s, const voice__voice__Params* params, onsa_span_f32 out) {
  uint32_t len = out.len;
  voice__voice__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float v;
    float onsa_t2 = voice__voice__tick(&(*s));
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "voice.onsa", 73)] = v;
  }
}

ONSA_INLINE void voice__voice__params_default(voice__voice__Params* out) {
  (*out) = ((voice__voice__Params){ .f0 = 110.0f, .vowel_f1 = 700.0f, .vowel_f2 = 1220.0f, .gain = 0.5f });
}

ONSA_INLINE void voice__echo__ctl(voice__echo__State* s, const voice__echo__Params* p) {
  s->feedback = p->feedback;
  float d = (float)(p->time * s->sample_rate);
  s->d = d;
}

ONSA_INLINE float voice__echo__tick(voice__echo__State* s, float x) {
  float onsa_t4 = x;
  float onsa_t3 = s->feedback;
  float vdelay_0_d = s->d;
  float vdelay_0_dc;
  if (vdelay_0_d >= 1.0f) {
    if (vdelay_0_d <= 96000.0f) {
      vdelay_0_dc = vdelay_0_d;
    } else {
      vdelay_0_dc = 96000.0f;
    }
  } else {
    vdelay_0_dc = 1.0f;
  }
  uint32_t vdelay_0_k = onsa_trunc_u32_f32(vdelay_0_dc, "voice.onsa", 99);
  float vdelay_0_f = (float)(vdelay_0_dc - ((float)vdelay_0_k));
  uint32_t vdelay_0_wlk = onsa_sub_u32(onsa_add_u32(s->vdelay_0_w, UINT32_C(96001), "voice.onsa", 91), vdelay_0_k, "voice.onsa", 91);
  uint32_t onsa_t1 = onsa_rem_u32(vdelay_0_wlk, UINT32_C(96001), "voice.onsa", 99);
  float vdelay_0_a = s->vdelay_0_buf.a[onsa_idx(onsa_t1, UINT32_C(96001), "voice.onsa", 91)];
  uint32_t onsa_t2 = onsa_rem_u32(onsa_sub_u32(vdelay_0_wlk, UINT32_C(1), "voice.onsa", 99), UINT32_C(96001), "voice.onsa", 99);
  float vdelay_0_b = s->vdelay_0_buf.a[onsa_idx(onsa_t2, UINT32_C(96001), "voice.onsa", 91)];
  float vdelay_0 = (float)((float)((float)(1.0f - vdelay_0_f) * vdelay_0_a) + (float)(vdelay_0_f * vdelay_0_b));
  float y = (float)(onsa_t4 + (float)(onsa_t3 * vdelay_0));
  float onsa__out = y;
  s->vdelay_0_buf.a[onsa_idx(s->vdelay_0_w, UINT32_C(96001), "voice.onsa", 91)] = y;
  s->vdelay_0_w = onsa_rem_u32(onsa_add_u32(s->vdelay_0_w, UINT32_C(1), "voice.onsa", 91), UINT32_C(96001), "voice.onsa", 91);
  return onsa__out;
}

ONSA_INLINE void voice__echo__init(voice__echo__State* out, const voice__echo__Config* cfg, float sample_rate) {
  (void)cfg;
  memset(&(*out), 0, sizeof (*out));
  out->sample_rate = sample_rate;
  float vdelay_0_init = 0.0f;
  {
    uint32_t onsa_i;
    for (onsa_i = 0; onsa_i < 96001; onsa_i++) out->vdelay_0_buf.a[onsa_i] = vdelay_0_init;
  }
  out->vdelay_0_w = UINT32_C(0);
  out->poisoned = false;
  out->initialized = true;
}

ONSA_INLINE void voice__echo__reset(voice__echo__State* s) {
  (void)s;
  {
    uint32_t onsa_i;
    for (onsa_i = 0; onsa_i < 96001; onsa_i++) s->vdelay_0_buf.a[onsa_i] = 0.0f;
  }
  s->vdelay_0_w = UINT32_C(0);
  s->poisoned = false;
}

ONSA_INLINE void voice__echo__process(voice__echo__State* s, const voice__echo__Params* params, onsa_span_f32 x, onsa_span_f32 out) {
  uint32_t len = x.len;
  if (out.len != len) {
    onsa_panic("span lengths differ", "voice.onsa", 91);
  }
  voice__echo__ctl(&(*s), &(*params));
  uint32_t onsa_t1 = len;
  for (uint32_t i = UINT32_C(0); i < onsa_t1; i++) {
    float x_11 = x.ptr[onsa_idx(i, x.len, "voice.onsa", 91)];
    float v;
    float onsa_t2 = voice__echo__tick(&(*s), x_11);
    v = onsa_t2;
    out.ptr[onsa_idx(i, out.len, "voice.onsa", 91)] = v;
  }
}

ONSA_INLINE void voice__echo__params_default(voice__echo__Params* out) {
  (*out) = ((voice__echo__Params){ .time = 0.3f, .feedback = 0.5f });
}

/* ---- called after the setjmp of a wrapper, never inlined there (R-167) ---- */
static ONSA_NOINLINE ONSA_UNUSED void voice__voice__init__guarded(voice__voice__State* out, const voice__voice__Config* cfg, float sample_rate) { voice__voice__init(out, cfg, sample_rate); }
static ONSA_NOINLINE ONSA_UNUSED void voice__voice__process__guarded(voice__voice__State* s, const voice__voice__Params* params, onsa_span_f32 out) { voice__voice__process(s, params, out); }
static ONSA_NOINLINE ONSA_UNUSED void voice__echo__init__guarded(voice__echo__State* out, const voice__echo__Config* cfg, float sample_rate) { voice__echo__init(out, cfg, sample_rate); }
static ONSA_NOINLINE ONSA_UNUSED void voice__echo__process__guarded(voice__echo__State* s, const voice__echo__Params* params, onsa_span_f32 x, onsa_span_f32 out) { voice__echo__process(s, params, x, out); }

/* ---- panic = "poison": the last exported function call panicked (spec §9.2) ---- */
static ONSA_THREAD_LOCAL int onsa_last_panic = 0;
int onsa_take_panic(void) { int p = onsa_last_panic; onsa_last_panic = 0; return p; }

/* ---- export: voice.voice ---- */
int onsa_voice_init(onsa_voice* s, void* bulk, float sample_rate) {
  voice__voice__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  (void)bulk;
  jmp_buf onsa_jb;
  jmp_buf* volatile onsa_prev = onsa_current_jmp;
  if (setjmp(onsa_jb)) {
    onsa_current_jmp = onsa_prev;
    memset(s, 0, sizeof(*s));
    return 1;
  }
  onsa_current_jmp = &onsa_jb;
  voice__voice__init__guarded(s, &cfg, sample_rate);
  onsa_current_jmp = onsa_prev;
  return 0;
}

void onsa_voice_reset(onsa_voice* s) { if (!s->initialized) return; voice__voice__reset(s); }

void onsa_voice_params_default(onsa_voice_params* p) { voice__voice__params_default(p); }

int onsa_voice_process(onsa_voice* s, const onsa_voice_params* p, float* out, uint32_t frames) {
  voice__voice__Params q;
  if (!s->initialized || s->poisoned) {
    if (frames != 0) {
      memset(out, 0, (size_t)frames * sizeof(float));
    }
    return 1;
  }
  q = *p;
  q.f0 = onsa_clamp_f32(q.f0, 20.0f, 2000.0f);
  q.vowel_f1 = onsa_clamp_f32(q.vowel_f1, 200.0f, 1200.0f);
  q.vowel_f2 = onsa_clamp_f32(q.vowel_f2, 600.0f, 3000.0f);
  q.gain = onsa_clamp_f32(q.gain, 0.0f, 1.0f);
  jmp_buf onsa_jb;
  jmp_buf* volatile onsa_prev = onsa_current_jmp;
  if (setjmp(onsa_jb)) {
    onsa_current_jmp = onsa_prev;
    if (frames != 0) {
      memset(out, 0, (size_t)frames * sizeof(float));
    }
    s->poisoned = true;
    return 1;
  }
  onsa_current_jmp = &onsa_jb;
  voice__voice__process__guarded(s, &q, onsa_span_f32_of(out, frames));
  onsa_current_jmp = onsa_prev;
  return 0;
}

const onsa_param_info onsa_voice_param_info[4] = {
  { "f0", "f0", 20.0f, 2000.0f, 110.0f, NAN, "Hz", "log", "" },
  { "vowel_f1", "vowel_f1", 200.0f, 1200.0f, 700.0f, NAN, "Hz", "linear", "" },
  { "vowel_f2", "vowel_f2", 600.0f, 3000.0f, 1220.0f, NAN, "Hz", "linear", "" },
  { "gain", "gain", 0.0f, 1.0f, 0.5f, NAN, "", "linear", "" },
};

/* ---- export: voice.echo ---- */
int onsa_echo_init(onsa_echo* s, void* bulk, float sample_rate) {
  voice__echo__Config cfg;
  memset(&cfg, 0, sizeof cfg);
  (void)bulk;
  jmp_buf onsa_jb;
  jmp_buf* volatile onsa_prev = onsa_current_jmp;
  if (setjmp(onsa_jb)) {
    onsa_current_jmp = onsa_prev;
    memset(s, 0, sizeof(*s));
    return 1;
  }
  onsa_current_jmp = &onsa_jb;
  voice__echo__init__guarded(s, &cfg, sample_rate);
  onsa_current_jmp = onsa_prev;
  return 0;
}

void onsa_echo_reset(onsa_echo* s) { if (!s->initialized) return; voice__echo__reset(s); }

void onsa_echo_params_default(onsa_echo_params* p) { voice__echo__params_default(p); }

int onsa_echo_process(onsa_echo* s, const onsa_echo_params* p, const float* x, float* out, uint32_t frames) {
  voice__echo__Params q;
  if (!s->initialized || s->poisoned) {
    if (frames != 0) {
      memset(out, 0, (size_t)frames * sizeof(float));
    }
    return 1;
  }
  if (frames != 0) {
    if (onsa_overlaps(x, (size_t)frames * sizeof(float), out, (size_t)frames * sizeof(float))) {
      memset(out, 0, (size_t)frames * sizeof(float));
      return 2;
    }
  }
  q = *p;
  q.time = onsa_clamp_f32(q.time, 0.01f, 1.0f);
  q.feedback = onsa_clamp_f32(q.feedback, 0.0f, 0.95f);
  jmp_buf onsa_jb;
  jmp_buf* volatile onsa_prev = onsa_current_jmp;
  if (setjmp(onsa_jb)) {
    onsa_current_jmp = onsa_prev;
    if (frames != 0) {
      memset(out, 0, (size_t)frames * sizeof(float));
    }
    s->poisoned = true;
    return 1;
  }
  onsa_current_jmp = &onsa_jb;
  voice__echo__process__guarded(s, &q, onsa_span_f32_of((float*)x, frames), onsa_span_f32_of(out, frames));
  onsa_current_jmp = onsa_prev;
  return 0;
}

const onsa_param_info onsa_echo_param_info[2] = {
  { "time", "time", 0.01f, 1.0f, 0.3f, NAN, "s", "linear", "" },
  { "feedback", "feedback", 0.0f, 0.95f, 0.5f, NAN, "", "linear", "" },
};

