/* ==== onsa_resonator.h ==== */
/* onsa_resonator.h — generated by onsa build for the flow `voice.resonator`; do not edit. */
#ifndef ONSA_RESONATOR_H
#define ONSA_RESONATOR_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_RESONATOR_SIZE      28   /* bytes of the fast region (spec §12.4) */
#define ONSA_RESONATOR_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_RESONATOR_ALIGN     4
#define ONSA_RESONATOR_PARAM_COUNT 2

typedef struct onsa_resonator onsa_resonator;   /* the state (fast region); opaque */
typedef struct onsa_resonator_params { float fc; float bw; } onsa_resonator_params;

/* Memory is the caller's: `s` has ONSA_RESONATOR_SIZE bytes aligned to ONSA_RESONATOR_ALIGN, `bulk` has ONSA_RESONATOR_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_resonator_init(onsa_resonator* s, void* bulk, float sample_rate);
void onsa_resonator_reset(onsa_resonator* s);   /* clears `poisoned`; no effect on an uninitialized instance */
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_resonator_process(onsa_resonator* s, const onsa_resonator_params* p, const float* x, float* out, uint32_t frames);
extern const onsa_param_info onsa_resonator_param_info[2];

/* Convenience on targets with a heap. */
onsa_resonator* onsa_resonator_new(float sample_rate);   /* NULL when out of memory or `init` panicked */
void onsa_resonator_free(onsa_resonator* s);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_RESONATOR_H */
/* ==== onsa_saw.h ==== */
/* onsa_saw.h — generated by onsa build for the flow `voice.saw`; do not edit. */
#ifndef ONSA_SAW_H
#define ONSA_SAW_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_SAW_SIZE      16   /* bytes of the fast region (spec §12.4) */
#define ONSA_SAW_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_SAW_ALIGN     4
#define ONSA_SAW_PARAM_COUNT 1

typedef struct onsa_saw onsa_saw;   /* the state (fast region); opaque */
typedef struct onsa_saw_params { float f0; } onsa_saw_params;

/* Memory is the caller's: `s` has ONSA_SAW_SIZE bytes aligned to ONSA_SAW_ALIGN, `bulk` has ONSA_SAW_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_saw_init(onsa_saw* s, void* bulk, float sample_rate);
void onsa_saw_reset(onsa_saw* s);   /* clears `poisoned`; no effect on an uninitialized instance */
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_saw_process(onsa_saw* s, const onsa_saw_params* p, float* out, uint32_t frames);
extern const onsa_param_info onsa_saw_param_info[1];

/* Convenience on targets with a heap. */
onsa_saw* onsa_saw_new(float sample_rate);   /* NULL when out of memory or `init` panicked */
void onsa_saw_free(onsa_saw* s);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_SAW_H */
/* ==== onsa_smooth.h ==== */
/* onsa_smooth.h — generated by onsa build for the flow `voice.smooth`; do not edit. */
#ifndef ONSA_SMOOTH_H
#define ONSA_SMOOTH_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_SMOOTH_SIZE      16   /* bytes of the fast region (spec §12.4) */
#define ONSA_SMOOTH_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_SMOOTH_ALIGN     4
#define ONSA_SMOOTH_PARAM_COUNT 1

typedef struct onsa_smooth onsa_smooth;   /* the state (fast region); opaque */
typedef struct onsa_smooth_params { float x; } onsa_smooth_params;

/* Memory is the caller's: `s` has ONSA_SMOOTH_SIZE bytes aligned to ONSA_SMOOTH_ALIGN, `bulk` has ONSA_SMOOTH_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_smooth_init(onsa_smooth* s, void* bulk, float time, float sample_rate);
void onsa_smooth_reset(onsa_smooth* s);   /* clears `poisoned`; no effect on an uninitialized instance */
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_smooth_process(onsa_smooth* s, const onsa_smooth_params* p, float* out, uint32_t frames);
extern const onsa_param_info onsa_smooth_param_info[1];

/* Convenience on targets with a heap. */
onsa_smooth* onsa_smooth_new(float time, float sample_rate);   /* NULL when out of memory or `init` panicked */
void onsa_smooth_free(onsa_smooth* s);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_SMOOTH_H */
/* ==== onsa_voice.h ==== */
/* onsa_voice.h — generated by onsa build for the flow `voice.voice`; do not edit. */
#ifndef ONSA_VOICE_H
#define ONSA_VOICE_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_VOICE_SIZE      92   /* bytes of the fast region (spec §12.4) */
#define ONSA_VOICE_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_VOICE_ALIGN     4
#define ONSA_VOICE_PARAM_COUNT 4

typedef struct onsa_voice onsa_voice;   /* the state (fast region); opaque */
typedef struct onsa_voice_params { float f0; float vowel_f1; float vowel_f2; float gain; } onsa_voice_params;

/* Memory is the caller's: `s` has ONSA_VOICE_SIZE bytes aligned to ONSA_VOICE_ALIGN, `bulk` has ONSA_VOICE_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_voice_init(onsa_voice* s, void* bulk, float sample_rate);
void onsa_voice_reset(onsa_voice* s);   /* clears `poisoned`; no effect on an uninitialized instance */
void onsa_voice_params_default(onsa_voice_params* p);
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_voice_process(onsa_voice* s, const onsa_voice_params* p, float* out, uint32_t frames);
extern const onsa_param_info onsa_voice_param_info[4];

/* Convenience on targets with a heap. */
onsa_voice* onsa_voice_new(float sample_rate);   /* NULL when out of memory or `init` panicked */
void onsa_voice_free(onsa_voice* s);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_VOICE_H */
/* ==== onsa_echo.h ==== */
/* onsa_echo.h — generated by onsa build for the flow `voice.echo`; do not edit. */
#ifndef ONSA_ECHO_H
#define ONSA_ECHO_H
#ifndef ONSA_PANIC_TRAP
#define ONSA_PANIC_TRAP
#endif
#include "onsa.h"
#ifdef __cplusplus
extern "C" {
#endif

#define ONSA_ECHO_SIZE      384024   /* bytes of the fast region (spec §12.4) */
#define ONSA_ECHO_BULK_SIZE 0   /* bytes of the bulk region */
#define ONSA_ECHO_ALIGN     4
#define ONSA_ECHO_PARAM_COUNT 2

typedef struct onsa_echo onsa_echo;   /* the state (fast region); opaque */
typedef struct onsa_echo_params { float time; float feedback; } onsa_echo_params;

/* Memory is the caller's: `s` has ONSA_ECHO_SIZE bytes aligned to ONSA_ECHO_ALIGN, `bulk` has ONSA_ECHO_BULK_SIZE (NULL when 0). */
/* 0: ok, 1: `init` panicked (panic = "poison" only): the state is left uninitialized — `process` returns 1
 * and `reset` does nothing until `init` succeeds (spec §14.2, S-27). */
int  onsa_echo_init(onsa_echo* s, void* bulk, float sample_rate);
void onsa_echo_reset(onsa_echo* s);   /* clears `poisoned`; no effect on an uninitialized instance */
void onsa_echo_params_default(onsa_echo_params* p);
/* 0: ok, 1: poisoned or uninitialized, 2: partially overlapping buffers (identical in/out pointers are in-place). */
int  onsa_echo_process(onsa_echo* s, const onsa_echo_params* p, const float* x, float* out, uint32_t frames);
extern const onsa_param_info onsa_echo_param_info[2];

/* Convenience on targets with a heap. */
onsa_echo* onsa_echo_new(float sample_rate);   /* NULL when out of memory or `init` panicked */
void onsa_echo_free(onsa_echo* s);

#ifdef __cplusplus
}
#endif
#endif /* ONSA_ECHO_H */
