"""The items of the gate (`tools/gate.sh`, Q-08), in the order they run.

To add an item, add one `Step`. An item may be listed in `tests/pending.toml`
(kind `gate`) only if it says `pendable=True`: the items that keep the gate
complete (formatting, lints, tests, the fuzzing, the spec examples, the list
itself, the static checks of W1-02, the self-tests, the fmt properties of W1-07)
are never pending. Later works add checks that wait for a later decision as
pendable items (the C checks of W1-06; the comment places of fmt, W1-07). The
CST round trip (W3-01) is never pending.

A pendable item may also apply the list case by case: the entries
`<item>/<case>` are the item's own to apply (the C checks, `onsa_tests::ccheck`;
the test vectors, `onsa_tests::vectors`); the gate applies only the entry of
the whole item. An item with `by_case_only=True` may be listed only by case
(`tools/pending.py` refuses its whole entry: it would hide every new failure).
An item with `expect_internal=True` may hold an internal error of the compiler
by a case entry with `expect = "internal"` (W1-04, W2-02). An item with
`counts_rows=True` counts the failing rows of a case: its case entries must
say how many (`rows = N`), and the item fails when the count differs.
"""
import sys
from dataclasses import dataclass
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
PY = (sys.executable, "-B")
# The C checks (Q-07, W1-06): one item per row of `onsa_tests::c::ITEMS`.
C_CHECK = ("cargo", "run", "-q", "-p", "onsa_tests", "--bin", "onsa_cases", "--", "--c")
# The test vectors against an implementation (W2-02): `interp` or `c`.
VECTORS = ("cargo", "run", "-q", "-p", "onsa_tests", "--bin", "onsa_cases", "--", "--vectors")


@dataclass(frozen=True)
class Step:
    name: str
    argv: tuple
    info: bool = False  # shows something for the parent to read; a failure to show it fails
    pendable: bool = False  # may be listed in tests/pending.toml
    stage_args: bool = False  # receives `--stage-end STAGE`
    gate_steps: bool = False  # receives `--gate-steps <pendable items>`
    by_case_only: bool = False  # a pendable item listed only by case (`<item>/<case>`)
    expect_internal: bool = False  # its case entries may say `expect = "internal"`
    counts_rows: bool = False  # its case entries must say `rows = N`, the failing rows they hold


STEPS = [
    Step("fmt", ("cargo", "fmt", "--all", "--", "--check")),
    Step("clippy", ("cargo", "clippy", "--workspace", "--all-targets", "--", "-D", "warnings")),
    Step("test", ("cargo", "test", "--workspace")),
    # The compiler does not fail inside on mutated inputs (Q-06, W1-04).
    Step("fuzz", (*PY, str(TOOLS / "fuzz.py"))),
    Step("spec-examples", (*PY, str(TOOLS / "check_spec_examples.py"))),
    Step("spec-sections", (*PY, str(TOOLS / "spec_sections.py"), "--check")),
    Step("pending", (*PY, str(TOOLS / "pending.py")), stage_args=True, gate_steps=True),
    Step("diag-registry", (*PY, str(TOOLS / "diag_codes.py"), "--registry")),
    Step("diag-negatives", (*PY, str(TOOLS / "diag_codes.py"), "--negatives")),
    Step("gap-marks", (*PY, str(TOOLS / "gap_marks.py"))),
    Step("builtin-names", (*PY, str(TOOLS / "builtin_names.py"))),
    # The test vectors of 3.3 / 3.4 (W2-01): regenerated byte for byte, the registry against the spec, the
    # cross-check recorded for this data.
    Step("vectors", (*PY, str(TOOLS / "vectors" / "gen.py"), "--check")),
    # The interpreter against the vectors (W2-02): one case per operation, `vectors-interp/<op>`.
    Step(
        "vectors-interp", (*VECTORS, "interp"), pendable=True, by_case_only=True, expect_internal=True, counts_rows=True
    ),
    Step("ignored-files", (*PY, str(TOOLS / "ignored_files.py"))),
    # The keywords of the lexer against the list of §2.2 (W3-02): one case per word, `keywords/<word>`.
    Step("keywords", (*PY, str(TOOLS / "keywords.py")), pendable=True, by_case_only=True),
    Step("gate-selftest", (*PY, str(TOOLS / "test_gate.py"))),
    Step("golden", (*PY, str(TOOLS / "gate.py"), "--golden"), info=True),
    Step("spec-coverage", (*PY, str(TOOLS / "spec_sections.py"), "--list"), info=True),
    # The generated C (Q-07, W1-06): Clang and gcc-15 with -Wall -Wextra -Werror -pedantic and
    # conformance, the sanitizers, x86_64 under Rosetta, the public headers in C11, C99 and C++11.
    # A `-strict` item keeps the warnings its pair switches off for a known cause
    # (`onsa_tests::c::GCC_KNOWN_OFF`): the list holds the strict one, the pair always runs.
    Step("c-clang", (*C_CHECK, "c-clang"), pendable=True),
    Step("c-gcc", (*C_CHECK, "c-gcc"), pendable=True),
    Step("c-gcc-strict", (*C_CHECK, "c-gcc-strict"), pendable=True),
    Step("c-sanitize", (*C_CHECK, "c-sanitize"), pendable=True),
    Step("c-x86", (*C_CHECK, "c-x86"), pendable=True),
    Step("c-header", (*C_CHECK, "c-header"), pendable=True),
    Step("c-header-strict", (*C_CHECK, "c-header-strict"), pendable=True),
    # The generated C against the vectors (W2-02), with every toolchain of the C checks:
    # one case per operation and toolchain, `vectors-c/<op>[<toolchain>]`.
    Step("vectors-c", (*VECTORS, "c"), pendable=True, by_case_only=True, counts_rows=True),
    # The properties of `onsa fmt` on perturbed case sources (Q-03, W1-07): the
    # same program, idempotence, the normal form of the code.
    Step("fmt-props", (*PY, str(TOOLS / "fmt_props.py"))),
    # Comments stay on the line of their element (R-70); listed until W3-11.
    Step("fmt-comments", (*PY, str(TOOLS / "fmt_props.py"), "--property", "comments"), pendable=True),
    # The CST gives the source back byte for byte (R-86, W3-01).
    Step("fmt-cst", (*PY, str(TOOLS / "fmt_props.py"), "--property", "cst")),
]


def pendable(steps=None):
    return [s.name for s in (STEPS if steps is None else steps) if s.pendable and not s.info]


def by_case_only(steps=None):
    """The pendable items that may be listed only by case."""
    return [s.name for s in (STEPS if steps is None else steps) if s.pendable and not s.info and s.by_case_only]


def expect_internal(steps=None):
    """The pendable items whose case entries may say `expect = "internal"`."""
    return [s.name for s in (STEPS if steps is None else steps) if s.pendable and not s.info and s.expect_internal]


def counts_rows(steps=None):
    """The pendable items whose case entries must say `rows = N`."""
    return [s.name for s in (STEPS if steps is None else steps) if s.pendable and not s.info and s.counts_rows]
